/* Bairro Unido - versão independente
   Frontend: GitHub Pages / qualquer hospedagem estática
   Backend opcional: Google Apps Script + Google Sheets
*/
const API_URL = localStorage.getItem('bairro_api_url') || '';
const KEY='bairro_unido_data_v1';
const defaultData={
  settings:{name:'Bairro Unido', subtitle:'Associação de Moradores', fee:10, apiUrl:API_URL},
  members:[], transactions:[], bookings:[]
};
let data=loadData();
let state={page:'home',homeMonth:new Date(),bookingMonth:new Date(),financeMonth:new Date(),financeFilter:'todos',memberSearch:'',memberMonth:monthKey(new Date())};

function loadData(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(data)); document.getElementById('syncText').textContent=API_URL?'Online + local':'Offline Ready'}
function uid(prefix='id'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)}
function fmtDate(v){if(!v)return '-';const [y,m,d]=String(v).slice(0,10).split('-');return d&&m&&y?`${d}/${m}/${y}`:v}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function monthLabel(d){return d.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase())}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),2500)}
function setPage(p){state.page=p;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('page-'+p).classList.add('active');render();document.getElementById('sidebar').classList.remove('open')}
function save(){persist();render()}
function openModal(html){document.getElementById('modalRoot').innerHTML=html;document.getElementById('modalBackdrop').classList.remove('hidden')}
function closeModal(){document.getElementById('modalRoot').innerHTML='';document.getElementById('modalBackdrop').classList.add('hidden')}
document.getElementById('modalBackdrop').addEventListener('click',closeModal);
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));

function calendarHTML(monthDate, bookings=[], compact=false){
 const y=monthDate.getFullYear(),m=monthDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=first.getDay();
 let h='<div class="calendar">'; ['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].forEach(x=>h+=`<div class="dow">${x}</div>`);
 for(let i=0;i<start;i++)h+='<div></div>';
 for(let day=1;day<=days;day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const bs=bookings.filter(b=>b.date===key);const today=new Date();const isToday=key===`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;h+=`<button class="day ${isToday?'today':''}" onclick="dayBooking('${key}')"><span>${day}</span>${bs.length?'<i class="dot"></i>':''}</button>`}
 return h+'</div>';
}
function calendarNav(type,date){return `<div class="month-nav"><strong>${monthLabel(date)}</strong><button class="mini-btn" onclick="moveMonth('${type}',-1)">‹</button><button class="mini-btn" onclick="moveMonth('${type}',1)">›</button></div>`}
function moveMonth(type,dir){state[type==='home'?'homeMonth':'bookingMonth'].setMonth(state[type==='home'?'homeMonth':'bookingMonth'].getMonth()+dir);render()}

function render(){document.getElementById('brandName').textContent=data.settings.name||'Bairro Unido';document.getElementById('mobileTitle').textContent=data.settings.name||'Bairro Unido';document.title=data.settings.name||'Bairro Unido';persist();
 if(state.page==='home')renderHome(); if(state.page==='financeiro')renderFinance(); if(state.page==='agendamentos')renderBookings(); if(state.page==='moradores')renderMembers(); if(state.page==='config')renderConfig();}

function renderHome(){const p=document.getElementById('page-home');const month=state.homeMonth;const mk=monthKey(month);const monthTx=data.transactions.filter(t=>String(t.date||'').slice(0,7)===mk);const income=monthTx.filter(t=>t.type==='receita').reduce((a,t)=>a+Number(t.value||0),0);const expense=monthTx.filter(t=>t.type==='despesa').reduce((a,t)=>a+Number(t.value||0),0);const balance=income-expense;const fee=data.settings.fee||0;const feeIncome=monthTx.filter(t=>t.category==='Taxa Mensal').reduce((a,t)=>a+Number(t.value||0),0);
 p.innerHTML=`<div class="hero-title"><div class="welcome">Bem-vindo de volta</div><h1>${escapeHtml(data.settings.name||'Bairro Unido')}</h1><div class="top-actions" style="justify-content:center"><span class="cash-chip">▣ Caixa: ${money(balance)}</span><button class="btn btn-primary" onclick="newTransaction()">＋ Novo Lançamento</button></div></div>
 <div class="grid-home"><div class="card card-pad"><div class="card-head"><h3>▦ Sala Comunitária</h3><button class="btn btn-small" onclick="newBooking()">＋ Agendar</button></div>${calendarNav('home',month)}${calendarHTML(month,data.bookings)}<div class="legend"><span><i></i>Livre</span><span><i class="pending"></i>Pendente</span><span><i class="reserved"></i>Reservado</span></div></div>
 <div class="side-stack"><div class="metric green"><div class="label">Saldo Atual</div><div class="value">${money(balance)}</div><div class="sub"><span class="green-text">↗ ${money(income)}</span><span class="red-text">↘ ${money(expense)}</span></div></div><div class="metric"><div class="card-head"><div class="label">Lançamentos Recentes</div><button class="btn btn-small" onclick="newTransaction()">＋ Adicionar</button></div>${monthTx.length?monthTx.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(t=>`<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eef1f5;font-size:12px"><span>${escapeHtml(t.description)}</span><b class="${t.type==='despesa'?'red-text':'green-text'}">${money(t.value)}</b></div>`).join(''):'<div class="empty">Nenhum lançamento ainda</div>'}</div><div class="metric"><div class="label">Taxa Mensal</div><div style="margin-top:8px;font-size:13px">Receitas de taxa mensal: <b>${money(feeIncome)}</b></div></div></div></div>`}

function renderFinance(){const p=document.getElementById('page-financeiro');const mk=monthKey(state.financeMonth);let tx=data.transactions.filter(t=>String(t.date||'').slice(0,7)===mk);if(state.financeFilter!=='todos')tx=tx.filter(t=>t.type===state.financeFilter);const q=(document.getElementById('financeSearch')?.value||'').toLowerCase();if(q)tx=tx.filter(t=>(t.description||'').toLowerCase().includes(q)||(t.category||'').toLowerCase().includes(q));const all=data.transactions.filter(t=>String(t.date||'').slice(0,7)===mk);const rec=all.filter(t=>t.type==='receita').reduce((a,t)=>a+Number(t.value||0),0),des=all.filter(t=>t.type==='despesa').reduce((a,t)=>a+Number(t.value||0),0);
 p.innerHTML=`<div class="page-title"><div><h1>Financeiro</h1><p>Controle de receitas e despesas da associação</p></div><div class="top-actions"><input class="search" type="month" value="${mk}" onchange="state.financeMonth=new Date(this.value+'-02');render()"><button class="btn" onclick="exportExcel()">⇩ Exportar Excel</button><button class="btn btn-primary" onclick="newTransaction()">＋ Novo Lançamento</button></div></div><div class="stats"><div class="stat green"><div class="label">Saldo</div><div class="number">${money(rec-des)}</div></div><div class="stat"><div class="label">Receitas</div><div class="number green-text">${money(rec)}</div></div><div class="stat"><div class="label">Despesas</div><div class="number red-text">${money(des)}</div></div></div><div class="filters"><button class="filter ${state.financeFilter==='todos'?'active':''}" onclick="state.financeFilter='todos';render()">Todos</button><button class="filter ${state.financeFilter==='receita'?'active':''}" onclick="state.financeFilter='receita';render()">Receitas</button><button class="filter ${state.financeFilter==='despesa'?'active':''}" onclick="state.financeFilter='despesa';render()">Despesas</button><input id="financeSearch" class="search" placeholder="⌕ Buscar..." value="${escapeHtml(q)}" oninput="filterFinance()"></div><div class="table-wrap">${tx.length?`<table class="table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Valor</th><th></th></tr></thead><tbody>${tx.map(t=>`<tr><td>${fmtDate(t.date)}</td><td>${escapeHtml(t.description)}</td><td>${escapeHtml(t.category)}</td><td><span class="status ${t.type==='despesa'?'despesa':'pago'}">${t.type==='despesa'?'Despesa':'Receita'}</span></td><td>${money(t.value)}</td><td><button class="btn btn-small" onclick="editTransaction('${t.id}')">Editar</button> <button class="btn btn-small btn-danger" onclick="deleteTransaction('${t.id}')">Excluir</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum lançamento encontrado</div>'}</div>`}
function filterFinance(){clearTimeout(filterFinance.t);filterFinance.t=setTimeout(render,180)}

function renderBookings(){const p=document.getElementById('page-agendamentos');const m=state.bookingMonth;const bs=data.bookings.filter(b=>String(b.date||'').slice(0,7)===monthKey(m));p.innerHTML=`<div class="page-title"><div><h1>Agendamentos</h1><p>Reservas da Sala Comunitária</p></div><button class="btn btn-primary" onclick="newBooking()">＋ Agendar Sala</button></div><div class="calendar-booking"><div class="card card-pad">${calendarNav('booking',m)}${calendarHTML(m,data.bookings)}<div class="legend"><span><i></i>Livre</span><span><i class="pending"></i>Pendente</span><span><i class="reserved"></i>Reservado</span></div></div><div class="card card-pad"><div class="card-head"><h3>Todas as reservas</h3><span class="muted">${bs.length}</span></div><div class="reservation-list" style="margin-top:14px">${bs.length?bs.sort((a,b)=>a.date.localeCompare(b.date)).map(b=>`<div class="reservation"><div style="display:flex;justify-content:space-between;gap:8px"><strong>${escapeHtml(b.name)}</strong><span class="status ${b.status.toLowerCase()}">${escapeHtml(b.status)}</span></div><small>${fmtDate(b.date)} · ${escapeHtml(b.time)} · ${escapeHtml(b.reason||'Evento')}</small><div style="margin-top:8px"><button class="btn btn-small" onclick="editBooking('${b.id}')">Editar</button> <button class="btn btn-small btn-danger" onclick="deleteBooking('${b.id}')">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhuma reserva ainda</div>'}</div></div></div>`}

function renderMembers(){const p=document.getElementById('page-moradores');const mk=state.memberMonth;let ms=data.members;const q=state.memberSearch.toLowerCase();if(q)ms=ms.filter(m=>`${m.name} ${m.address} ${m.phone}`.toLowerCase().includes(q));const paidIds=new Set(data.transactions.filter(t=>t.type==='receita'&&t.category==='Taxa Mensal'&&String(t.date).slice(0,7)===mk).map(t=>t.memberId).filter(Boolean));const paid=ms.filter(m=>paidIds.has(m.id)).length;const pending=ms.filter(m=>!m.exempt&&!paidIds.has(m.id)).length;const total=data.members.filter(m=>paidIds.has(m.id)).reduce((a,m)=>a+(Number(m.fee||data.settings.fee)||0),0);
 p.innerHTML=`<div class="page-title"><div><h1>Moradores</h1><p>Cadastro e pagamento da taxa mensal</p></div><button class="btn btn-primary" onclick="newMember()">＋ Cadastrar</button></div><div class="stats four"><div class="stat"><div class="label">Moradores</div><div class="number">${data.members.length}</div></div><div class="stat green"><div class="label">Pagos</div><div class="number">${paid}</div></div><div class="stat amber"><div class="label">Pendentes</div><div class="number">${pending}</div></div><div class="stat"><div class="label">Arrecadado</div><div class="number">${money(total)}</div></div></div><div class="filters"><button class="filter active">Taxa de ${monthLabel(new Date(mk+'-02'))}</button><input class="search" placeholder="⌕ Buscar morador..." value="${escapeHtml(state.memberSearch)}" oninput="state.memberSearch=this.value;render()"></div><div class="table-wrap">${ms.length?`<table class="table"><thead><tr><th>Morador</th><th>Casa</th><th>Telefone</th><th>Taxa</th><th>Status</th><th>Ações</th></tr></thead><tbody>${ms.map(m=>{const isPaid=paidIds.has(m.id);return `<tr><td><b>${escapeHtml(m.name)}</b>${m.exempt?'<div class="muted">Isento</div>':''}</td><td>${escapeHtml(m.address||'-')}</td><td>${escapeHtml(m.phone||'-')}</td><td>${money(m.fee||data.settings.fee)}</td><td>${m.exempt?'<span class="status confirmado">Isento</span>':`<span class="status ${isPaid?'pago':'pendente'}">${isPaid?'Pago':'Pendente'}</span>`}</td><td>${!m.exempt&&!isPaid?`<button class="btn btn-small btn-primary" onclick="payMember('${m.id}')">Pagar</button>`:''} <button class="btn btn-small" onclick="editMember('${m.id}')">Editar</button> <button class="btn btn-small btn-danger" onclick="deleteMember('${m.id}')">Excluir</button></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">Nenhum morador cadastrado ainda</div>'}</div>`}

function renderConfig(){const p=document.getElementById('page-config');p.innerHTML=`<div class="page-title"><div><h1>Configurações</h1><p>Ajustes da associação e do sistema</p></div></div><div class="config-stack"><div class="card card-pad"><h3>⚙ Dados da Associação</h3><div class="form-grid" style="margin-top:16px"><div class="field full"><label>Nome da Associação</label><input id="cfgName" value="${escapeHtml(data.settings.name)}"></div><div class="field"><label>Valor da Taxa Mensal (por morador)</label><input id="cfgFee" type="number" min="0" step="0.01" value="${Number(data.settings.fee||0)}"></div><div class="field"><label>URL do Google Apps Script</label><input id="cfgApi" placeholder="https://script.google.com/macros/s/.../exec" value="${escapeHtml(data.settings.apiUrl||'')}"></div></div><button class="btn btn-primary" style="margin-top:15px" onclick="saveConfig()">Salvar Configurações</button></div><div class="card card-pad"><h3>↕ Backup e Restauração</h3><p class="help">Exporte todos os dados para um arquivo JSON e guarde uma cópia. A restauração substitui os dados locais deste dispositivo.</p><div class="top-actions"><button class="btn" onclick="backup()">Exportar Backup</button><button class="btn" onclick="document.getElementById('restoreFile').click()">Restaurar Backup</button><input id="restoreFile" type="file" accept="application/json" hidden onchange="restore(event)"></div></div><div class="card card-pad"><h3>☁ Sincronização</h3><p class="help">O aplicativo funciona sem internet usando o armazenamento local. Quando configurarmos o Google Apps Script, os cadastros, lançamentos e reservas poderão ser sincronizados com o Google Sheets.</p><div class="code-box">${API_URL?escapeHtml(API_URL):'Google Apps Script ainda não configurado'}</div><div class="top-actions" style="margin-top:12px"><button class="btn" onclick="syncFromCloud()">↻ Buscar dados da planilha</button></div></div><div class="card card-pad"><h3>💻 Usar no celular/computador</h3><p class="help">Publique estes arquivos no GitHub Pages. No celular, abra o endereço no navegador e use “Adicionar à tela inicial”/“Instalar aplicativo”.</p></div></div>`}

function newTransaction(existing=null){const t=existing||{id:uid('tx'),type:'receita',description:'',value:'',date:new Date().toISOString().slice(0,10),category:'Taxa Mensal'};openModal(`<div class="modal"><div class="modal-head"><h2>${existing?'Editar':'Novo'} Lançamento</h2><button class="close" onclick="closeModal()">×</button></div><div class="toggle"><button id="recBtn" class="${t.type==='receita'?'active':''}" onclick="setTxType('receita')">↑ Receita</button><button id="desBtn" class="${t.type==='despesa'?'active':''}" onclick="setTxType('despesa')">↓ Despesa</button></div><input type="hidden" id="txType" value="${t.type}"><div class="form-grid"><div class="field full"><label>Descrição</label><input id="txDesc" value="${escapeHtml(t.description)}" placeholder="Ex: Taxa mensal - Casa 12"></div><div class="field"><label>Valor (R$)</label><input id="txValue" type="number" step="0.01" min="0" value="${t.value}"></div><div class="field"><label>Data</label><input id="txDate" type="date" value="${t.date}"></div><div class="field full"><label>Categoria</label><div class="chips">${['Taxa Mensal','Aluguel Sala','Doação','Evento','Manutenção','Contas/Despesas','Outro'].map(c=>`<button type="button" class="chip" onclick="document.getElementById('txCat').value='${c}'">${c}</button>`).join('')}</div><input id="txCat" value="${escapeHtml(t.category||'Outro')}" style="margin-top:8px"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveTransaction('${t.id}')">Salvar</button></div></div>`)}
function setTxType(type){document.getElementById('txType').value=type;document.getElementById('recBtn').classList.toggle('active',type==='receita');document.getElementById('desBtn').classList.toggle('active',type==='despesa')}
function saveTransaction(id){const t={id,type:document.getElementById('txType').value,description:document.getElementById('txDesc').value.trim(),value:Number(document.getElementById('txValue').value||0),date:document.getElementById('txDate').value,category:document.getElementById('txCat').value.trim()||'Outro'};if(!t.description||t.value<=0||!t.date)return showToast('Preencha descrição, valor e data.');const i=data.transactions.findIndex(x=>x.id===id);if(i>=0)data.transactions[i]=t;else data.transactions.push(t);closeModal();save();syncItem('transactions','upsert',t);showToast('Lançamento salvo.')}
function editTransaction(id){newTransaction(data.transactions.find(t=>t.id===id))}
function deleteTransaction(id){if(!confirm('Excluir este lançamento?'))return;data.transactions=data.transactions.filter(t=>t.id!==id);save();syncItem('transactions','delete',{id});showToast('Lançamento excluído.')}

function newMember(existing=null){const m=existing||{id:uid('m'),name:'',address:'',phone:'',email:'',notes:'',exempt:false,fee:Number(data.settings.fee||0)};openModal(`<div class="modal"><div class="modal-head"><h2>${existing?'Editar':'Cadastrar'} Morador</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field full"><label>Nome do Morador *</label><input id="mName" value="${escapeHtml(m.name)}" placeholder="Ex: Maria Silva"></div><div class="field"><label>Casa / Residência</label><input id="mAddress" value="${escapeHtml(m.address)}" placeholder="Ex: Rua das Flores, 23"></div><div class="field"><label>Telefone / WhatsApp</label><input id="mPhone" value="${escapeHtml(m.phone)}"></div><div class="field full"><label>E-mail</label><input id="mEmail" value="${escapeHtml(m.email)}" type="email"></div><div class="field full"><label>Observações</label><textarea id="mNotes" rows="3">${escapeHtml(m.notes)}</textarea></div><div class="field full"><label class="check"><input id="mExempt" type="checkbox" ${m.exempt?'checked':''}> Isento da taxa mensal</label></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveMember('${m.id}')">Salvar</button></div></div>`)}
function saveMember(id){const m={id,name:document.getElementById('mName').value.trim(),address:document.getElementById('mAddress').value.trim(),phone:document.getElementById('mPhone').value.trim(),email:document.getElementById('mEmail').value.trim(),notes:document.getElementById('mNotes').value.trim(),exempt:document.getElementById('mExempt').checked,fee:Number(data.settings.fee||0)};if(!m.name)return showToast('Informe o nome do morador.');const i=data.members.findIndex(x=>x.id===id);if(i>=0)data.members[i]=m;else data.members.push(m);closeModal();save();syncItem('members','upsert',m);showToast('Morador salvo.')}
function editMember(id){newMember(data.members.find(m=>m.id===id))}
function deleteMember(id){if(!confirm('Excluir este morador?'))return;data.members=data.members.filter(m=>m.id!==id);save();syncItem('members','delete',{id});showToast('Morador excluído.')}
function payMember(id){const m=data.members.find(x=>x.id===id);if(!m)return;const date=new Date();const tx={id:uid('tx'),type:'receita',description:`Taxa mensal - ${m.name}`,value:Number(m.fee||data.settings.fee||0),date:date.toISOString().slice(0,10),category:'Taxa Mensal',memberId:m.id};data.transactions.push(tx);save();syncItem('transactions','upsert',tx);showToast('Pagamento registrado.');}

function newBooking(existing=null,date=''){const b=existing||{id:uid('b'),name:'',date:date||new Date().toISOString().slice(0,10),phone:'',time:'08:00 - 10:00',reason:'',status:'Pendente'};openModal(`<div class="modal"><div class="modal-head"><h2>${existing?'Editar':'Agendar'} Sala Comunitária</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field full"><label>Nome do Morador</label><input id="bName" value="${escapeHtml(b.name)}" placeholder="Ex: Maria Silva - Casa 23"></div><div class="field"><label>Data</label><input id="bDate" type="date" value="${b.date}"></div><div class="field"><label>Contato</label><input id="bPhone" value="${escapeHtml(b.phone)}" placeholder="Telefone/WhatsApp"></div><div class="field full"><label>Horário</label><div class="time-grid">${['08:00 - 10:00','10:00 - 12:00','13:00 - 15:00','15:00 - 17:00','18:00 - 20:00','20:00 - 22:00'].map(x=>`<button type="button" class="time-btn ${b.time===x?'active':''}" onclick="selectTime(this,'${x}')">${x}</button>`).join('')}</div><input type="hidden" id="bTime" value="${escapeHtml(b.time)}"></div><div class="field full"><label>Motivo / Evento</label><input id="bReason" value="${escapeHtml(b.reason)}" placeholder="Ex: Aniversário infantil"></div><div class="field full"><label>Status</label><div class="toggle"><button id="pendBtn" class="${b.status==='Pendente'?'active':''}" onclick="setBookStatus('Pendente')">Pendente</button><button id="confBtn" class="${b.status==='Confirmado'?'active':''}" onclick="setBookStatus('Confirmado')">Confirmado</button></div><input type="hidden" id="bStatus" value="${b.status}"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveBooking('${b.id}')">Agendar Sala</button></div></div>`)}
function selectTime(el,v){document.querySelectorAll('.time-btn').forEach(x=>x.classList.remove('active'));el.classList.add('active');document.getElementById('bTime').value=v}
function setBookStatus(v){document.getElementById('bStatus').value=v;document.getElementById('pendBtn').classList.toggle('active',v==='Pendente');document.getElementById('confBtn').classList.toggle('active',v==='Confirmado')}
function saveBooking(id){const b={id,name:document.getElementById('bName').value.trim(),date:document.getElementById('bDate').value,phone:document.getElementById('bPhone').value.trim(),time:document.getElementById('bTime').value,reason:document.getElementById('bReason').value.trim(),status:document.getElementById('bStatus').value};if(!b.name||!b.date)return showToast('Informe nome e data.');const clash=data.bookings.find(x=>x.date===b.date&&x.time===b.time&&x.id!==id);if(clash)return showToast('Esse horário já está reservado.');const i=data.bookings.findIndex(x=>x.id===id);if(i>=0)data.bookings[i]=b;else data.bookings.push(b);closeModal();save();syncItem('bookings','upsert',b);showToast('Reserva salva.')}
function editBooking(id){newBooking(data.bookings.find(b=>b.id===id))}
function deleteBooking(id){if(!confirm('Excluir esta reserva?'))return;data.bookings=data.bookings.filter(b=>b.id!==id);save();syncItem('bookings','delete',{id});showToast('Reserva excluída.')}
function dayBooking(date){const b=data.bookings.filter(x=>x.date===date);if(b.length)editBooking(b[0].id);else newBooking(null,date)}

function saveConfig(){data.settings.name=document.getElementById('cfgName').value.trim()||'Bairro Unido';data.settings.fee=Number(document.getElementById('cfgFee').value||0);data.settings.apiUrl=document.getElementById('cfgApi').value.trim();localStorage.setItem('bairro_api_url',data.settings.apiUrl);persist();render();showToast('Configurações salvas.')}
function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});downloadBlob(blob,`backup-bairro-unido-${new Date().toISOString().slice(0,10)}.json`)}
function restore(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.members||!x.transactions||!x.bookings)throw Error();data=x;persist();render();showToast('Backup restaurado.')}catch{showToast('Arquivo de backup inválido.')}};r.readAsText(f)}
function exportExcel(){const rows=data.transactions.map(t=>({Data:fmtDate(t.date),Descrição:t.description,Categoria:t.category,Tipo:t.type==='receita'?'Receita':'Despesa',Valor:Number(t.value||0)}));if(!rows.length)return showToast('Não há lançamentos para exportar.');const csv=['Data;Descrição;Categoria;Tipo;Valor',...rows.map(r=>[r.Data,r.Descrição,r.Categoria,r.Tipo,r.Valor.toFixed(2).replace('.',',')].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';'))].join('\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`financeiro-${monthKey(state.financeMonth)}.csv`);showToast('Arquivo CSV compatível com Excel exportado.')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

async function syncFromCloud(){if(!data.settings.apiUrl)return showToast('Configure primeiro a URL do Google Apps Script.');try{const r=await fetch(data.settings.apiUrl);const x=await r.json();if(x.ok===false)throw Error(x.error||'Erro');data.members=x.members||[];data.transactions=x.transactions||[];data.bookings=x.bookings||[];if(x.settings)data.settings={...data.settings,...x.settings};persist();render();showToast('Dados sincronizados da planilha.')}catch(e){showToast('Não foi possível buscar a planilha agora.')}}
async function syncItem(sheet,action,item){const url=data.settings.apiUrl;if(!url)return;try{await fetch(url,{method:'POST',body:new URLSearchParams({action,sheet,payload:JSON.stringify(item)})})}catch(e){console.warn('sync',e)}}

window.newTransaction=newTransaction;window.editTransaction=editTransaction;window.deleteTransaction=deleteTransaction;window.setTxType=setTxType;window.newMember=newMember;window.editMember=editMember;window.deleteMember=deleteMember;window.payMember=payMember;window.newBooking=newBooking;window.editBooking=editBooking;window.deleteBooking=deleteBooking;window.selectTime=selectTime;window.setBookStatus=setBookStatus;window.dayBooking=dayBooking;window.moveMonth=moveMonth;window.saveConfig=saveConfig;window.backup=backup;window.restore=restore;window.exportExcel=exportExcel;window.syncFromCloud=syncFromCloud;window.closeModal=closeModal;window.filterFinance=filterFinance;
render();
