import React,{useEffect,useMemo,useState}from"react";
import{Routes,Route,NavLink}from"react-router-dom";
import{Home,WalletCards,CalendarDays,Users,Settings,Plus,Pencil,Trash2,Search,Download,Upload,RefreshCw,CheckCircle,ChevronLeft,ChevronRight,BarChart3,Menu,X,AlertTriangle,FileText,Receipt,UserRound,TrendingUp,TrendingDown,History,Printer,ArrowUpRight,ArrowDownRight}from"lucide-react";
import{getAll,create,update,remove,saveSettings,togglePayment,restoreBackup}from"./lib/api";
import{loadCache,saveCache,backupData,importBackup}from"./lib/storage";
import{brl,parseMoney,dateBR,todayISO,currentMonth,monthLabel,previousMonth,nextMonth,categories,slots,csvDownload,uid}from"./lib/utils";
const BRAND_SHORT="AMVF2";
const BRAND_FULL="Associação de Moradores do Vila Floresta 2";
function Brand({compact=false}){return <div className={`brand ${compact?"brand-compact":""}`}><img src={`${import.meta.env.BASE_URL}logo-amvf2.jpg`} alt="Logo AMVF2"/><div className="brand-text"><strong>{BRAND_SHORT}</strong>{!compact&&<small>{BRAND_FULL}</small>}</div></div>}
const nav=[["/","Início",Home],["/financeiro","Financeiro",WalletCards],["/inadimplencia","Inadimplência",AlertTriangle],["/relatorios","Prestação de contas",BarChart3],["/agendamentos","Agendamentos",CalendarDays],["/reunioes","Reuniões / Assembleias",FileText],["/moradores","Moradores",Users],["/configuracoes","Configurações",Settings]];
function Layout({data,refresh,setData}){const[menuOpen,setMenuOpen]=useState(false);const closeMenu=()=>setMenuOpen(false);return <><aside className="desktop-only" style={{position:"fixed",inset:"0 auto 0 0",width:250,padding:22,background:"#fff",borderRight:"1px solid #e2e8f0",zIndex:20}}><Brand/><nav style={{display:"grid",gap:7,marginTop:25}}>{nav.map(([p,l,I])=><NavLink key={p} to={p} style={({isActive})=>({padding:11,borderRadius:10,textDecoration:"none",fontWeight:700,color:isActive?"#047857":"#475569",background:isActive?"#ecfdf5":"transparent",display:"flex",gap:10,alignItems:"center"})}><I size={18}/>{l}</NavLink>)}</nav><button className="btn btn-gray" style={{width:"100%",marginTop:30,display:"flex",alignItems:"center",justifyContent:"center",gap:8}} onClick={refresh}><RefreshCw size={15}/> Atualizar</button></aside><header className="mobile-only mobile-header"><button className="mobile-menu-btn" aria-label="Abrir menu" onClick={()=>setMenuOpen(true)}><Menu size={23}/></button><Brand compact/></header>{menuOpen&&<><button className="mobile-menu-overlay" aria-label="Fechar menu" onClick={closeMenu}/><aside className="mobile-drawer"><div className="mobile-drawer-head"><Brand/><button className="btn btn-gray mobile-close-btn" aria-label="Fechar menu" onClick={closeMenu}><X size={19}/></button></div><nav className="mobile-nav">{nav.map(([p,l,I])=><NavLink key={p} to={p} onClick={closeMenu} className={({isActive})=>`mobile-nav-link ${isActive?"active":""}`}><I size={19}/><span>{l}</span></NavLink>)}</nav><button className="btn btn-gray mobile-refresh" onClick={()=>{closeMenu();refresh()}}><RefreshCw size={16}/> Atualizar</button></aside></>}<main className="main-content" style={{marginLeft:250,padding:"30px"}}><Routes><Route path="/" element={<HomePage data={data}/>}/><Route path="/financeiro" element={<Finance data={data} refresh={refresh}/>}/><Route path="/inadimplencia" element={<Delinquency data={data}/>}/><Route path="/relatorios" element={<Reports data={data}/>}/><Route path="/agendamentos" element={<Bookings data={data} refresh={refresh}/>}/><Route path="/reunioes" element={<Meetings data={data} refresh={refresh}/>}/><Route path="/moradores" element={<Residents data={data} refresh={refresh} setData={setData}/>}/><Route path="/configuracoes" element={<Config data={data} refresh={refresh} setData={setData}/>}/></Routes></main></>}
function Head({t,s,a}){return <div style={{display:"flex",justifyContent:"space-between",gap:12,marginBottom:20,alignItems:"center",flexWrap:"wrap"}}><div><h1 style={{margin:0,fontSize:27}}>{t}</h1><div style={{color:"#64748b"}}>{s}</div></div>{a}</div>}
function Stat({t,v}){return <div className="card" style={{padding:17}}><small style={{color:"#64748b",fontWeight:700}}>{t}</small><div style={{fontSize:24,fontWeight:900,marginTop:6}}>{v}</div></div>}
function Modal({title,close,children}){return <div style={{position:"fixed",inset:0,zIndex:50,background:"#0006",display:"grid",placeItems:"center",padding:15}}><div className="card" style={{padding:22,width:"min(600px,100%)",maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{marginTop:0}}>{title}</h2><button className="btn btn-gray" onClick={close}>✕</button></div>{children}</div></div>}
const F=({l,children})=><label className="label" style={{marginBottom:12}}>{l}{children}</label>;
async function safe(fn){try{return await fn()}catch(e){alert(e.message||String(e));return null}}

// Normaliza datas vindas do Google Sheets (que podem chegar como ISO com horário)
// para o formato usado pelo calendário: AAAA-MM-DD.
function bookingDate(value){
  if(!value)return "";
  const s=String(value).trim();
  if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;
  if(/^\d{4}-\d{2}-\d{2}T/.test(s))return s.slice(0,10);
  const br=s.match(/^(\d{2})[\/\-](\d{2})[\/\-](\d{4})/);
  if(br)return `${br[3]}-${br[2]}-${br[1]}`;
  const d=new Date(s);
  if(!Number.isNaN(d.getTime()))return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
  return s.slice(0,10);
}
function monthsUntilCurrentYear(){
  const now=currentMonth(), y=Number(now.slice(0,4)), m=Number(now.slice(5,7));
  return Array.from({length:m},(_,i)=>`${y}-${String(i+1).padStart(2,"0")}`);
}
function residentStartMonth(resident){
  const raw=String(resident?.created_date||"").trim();
  if(!raw)return "";
  if(/^\d{4}-\d{2}/.test(raw))return raw.slice(0,7);
  const d=new Date(raw);
  if(Number.isNaN(d.getTime()))return "";
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
}
function residentPendingMonths(resident){
  if(resident?.exempt)return [];
  const paid=new Set((resident?.paidMonths||[]).map(String));
  const start=residentStartMonth(resident);
  return monthsUntilCurrentYear().filter(m=>(!start||m>=start)&&!paid.has(m));
}
function paymentTotalsForResident(data,resident){
  const ids=new Set(Object.values(resident?.monthlyPaymentIds||{}).map(String));
  return (data.transactions||[]).filter(x=>ids.has(String(x.id))&&x.type==="income").reduce((a,x)=>a+Number(x.amount||0),0);
}
function HomePage({data}){
  const t=data.transactions||[],r=data.residents||[],b=data.bookings||[],m=currentMonth(),active=r.filter(x=>!x.exempt&&!x.inactive),paid=active.filter(x=>(x.paidMonths||[]).includes(m)),
    income=t.filter(x=>x.type==="income").reduce((a,x)=>a+Number(x.amount||0),0),expense=t.filter(x=>x.type==="expense").reduce((a,x)=>a+Number(x.amount||0),0),
    monthIncome=t.filter(x=>x.type==="income"&&String(x.date).slice(0,7)===m).reduce((a,x)=>a+Number(x.amount||0),0),monthExpense=t.filter(x=>x.type==="expense"&&String(x.date).slice(0,7)===m).reduce((a,x)=>a+Number(x.amount||0),0),
    fee=Number(data.settings?.taxaMensal||0),pending=active.filter(x=>!(x.paidMonths||[]).includes(m)),openValue=pending.length*fee,
    monthBookings=b.filter(x=>bookingDate(x.date).slice(0,7)===m),balance=income-expense,rate=active.length?Math.round((paid.length/active.length)*100):0;
  const upcoming=b.filter(x=>bookingDate(x.date)>=todayISO()).sort((x,y)=>(bookingDate(x.date)+x.timeSlot).localeCompare(bookingDate(y.date)+y.timeSlot)).slice(0,5);
  return <>
    <Head t="Painel administrativo" s="Visão geral da Associação de Moradores do Vila Floresta 2"/>
    <div className="admin-hero card"><div><span className="eyebrow">SITUAÇÃO DA ASSOCIAÇÃO</span><h2>Controle da diretoria</h2><p>Resumo financeiro, mensalidades e reservas em um só lugar.</p></div><div className="hero-balance"><small>Saldo atual</small><strong>{brl(balance)}</strong></div></div>
    <div className="admin-stats">
      <Stat t="Total recebido no mês" v={brl(monthIncome)}/><Stat t="Total de despesas" v={brl(monthExpense)}/><Stat t="Mensalidades pagas" v={`${paid.length} / ${active.length}`}/><Stat t="Mensalidades pendentes" v={pending.length}/><Stat t="Total a receber" v={brl(openValue)}/><Stat t="Reservas do mês" v={monthBookings.length}/><Stat t="Moradores cadastrados" v={r.filter(x=>!x.inactive).length}/><Stat t="Saldo atual" v={brl(balance)}/>
    </div>
    <div className="dashboard-grid">
      <div className="card dashboard-panel"><div className="panel-head"><div><h3>Indicadores rápidos</h3><small>Competência {monthLabel(m)}</small></div><span className={`rate-pill ${rate>=80?"good":rate>=50?"warn":"bad"}`}>{rate}% recebido</span></div><div className="progress"><div style={{width:`${rate}%`}}/></div><div className="indicator-grid"><div><b>{rate}%</b><span>das mensalidades recebidas</span></div><div><b>{brl(openValue)}</b><span>em aberto no mês</span></div><div><b>{monthBookings.length}</b><span>reservas este mês</span></div></div></div>
      <div className="card dashboard-panel"><div className="panel-head"><div><h3>Entradas x saídas</h3><small>{monthLabel(m)}</small></div><TrendingUp size={20}/></div><div className="mini-bars"><div><span>Entradas</span><b>{brl(monthIncome)}</b><i style={{width:`${monthIncome+monthExpense?Math.round(monthIncome/(monthIncome+monthExpense)*100):0}%`}}/></div><div><span>Saídas</span><b>{brl(monthExpense)}</b><i style={{width:`${monthIncome+monthExpense?Math.round(monthExpense/(monthIncome+monthExpense)*100):0}%`}}/></div></div></div>
    </div>
    <div className="dashboard-grid">
      <div className="card dashboard-panel"><div className="panel-head"><h3>Próximas reservas</h3><span className="badge badge-green">{upcoming.length}</span></div>{upcoming.length?upcoming.map(x=><div key={x.id} className="dashboard-row"><div><b>{x.residentName||"Reserva avulsa"}</b><small>{dateBR(bookingDate(x.date))} · {x.timeSlot}</small></div><strong>{brl(x.totalAmount||0)}</strong></div>):<div className="empty-state">Nenhuma reserva futura.</div>}</div>
      <div className="card dashboard-panel"><div className="panel-head"><h3>Maiores pendências</h3><span className="badge badge-yellow">{pending.length}</span></div>{pending.slice().sort((a,b)=>residentPendingMonths(b).length-residentPendingMonths(a).length).slice(0,5).map(x=><div key={x.id} className="dashboard-row"><div><b>{x.name}</b><small>{residentPendingMonths(x).length} mês(es) em aberto</small></div><strong>{brl(residentPendingMonths(x).length*fee)}</strong></div>)}{!pending.length&&<div className="empty-state">Nenhuma mensalidade pendente.</div>}</div>
    </div>
  </>;
}
function Finance({data,refresh}){
  const [filter,setFilter]=useState("all"),[q,setQ]=useState(""),[edit,setEdit]=useState(null),[open,setOpen]=useState(false);
  const payments=data.payments||[];
  const bookings=data.bookings||[];
  const month=currentMonth();
  const monthPayments=payments.filter(x=>String(x.date||"").slice(0,7)===month);
  const received=monthPayments.reduce((a,x)=>a+Number(x.amount||0),0);
  const contracted=bookings.filter(x=>bookingDate(x.date).slice(0,7)===month).reduce((a,x)=>a+Number(x.totalAmount||0),0);
  const due=Math.max(0,contracted-received);
  let items=(data.transactions||[]).filter(x=>(filter==="all"||x.type===filter)&&(`${x.description} ${x.category}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>String(b.date).localeCompare(a.date));
  let save=async f=>{let o={...f,amount:parseMoney(f.amount),method:f.method||"",created_date:edit?.created_date||new Date().toISOString()};let r=await safe(()=>edit?update("Transactions",edit.id,o):create("Transactions",{...o,id:uid()}));if(!r)return;saveCache({...data,transactions:edit?data.transactions.map(x=>x.id===edit.id?r:x):[r,...data.transactions]});setOpen(false);await refresh()};
  let del=async id=>{if(!confirm("Excluir este lançamento?"))return;let r=await safe(()=>remove("Transactions",id));if(!r)return;saveCache({...data,transactions:data.transactions.filter(x=>x.id!==id)});await refresh()};
  let csv=()=>csvDownload(`lancamentos_financeiros_${currentMonth()}.csv`,[["Data","Tipo","Categoria","Descrição","Forma","Valor (R$)"],...items.filter(x=>String(x.date).startsWith(currentMonth())).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>[x.date,x.type==="income"?"Entrada":"Saída",categories[x.category]||x.category,x.description,methods[x.method]||x.method||"",x.amount])]);
  const methods={pix:"Pix",cash:"Dinheiro",credit:"Cartão de crédito",debit:"Cartão de débito",transfer:"Transferência",other:"Outro"};
  return <><Head t="Financeiro" s="Entradas, despesas e recebimentos" a={<div style={{display:"flex",gap:8}}><button className="btn btn-primary" onClick={()=>{setEdit(null);setOpen(true)}}><Plus/> Novo lançamento</button></div>}/>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginBottom:16}}><Stat t="Saldo" v={brl((data.transactions||[]).filter(x=>x.type==="income").reduce((a,x)=>a+Number(x.amount||0),0)-(data.transactions||[]).filter(x=>x.type==="expense").reduce((a,x)=>a+Number(x.amount||0),0))}/><Stat t="Recebido no mês" v={brl(received)}/><Stat t="Contratado no mês" v={brl(contracted)}/><Stat t="A receber" v={brl(due)}/></div>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:13}}>{[["all","Todos"],["income","Entradas"],["expense","Despesas"]].map(([x,l])=><button key={x} className="btn btn-gray" onClick={()=>setFilter(x)}>{l}</button>)}<input className="input" style={{maxWidth:300}} placeholder="Buscar..." value={q} onChange={e=>setQ(e.target.value)}/></div>
    <div className="card" style={{padding:8,overflow:"auto"}}><table><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Forma</th><th>Valor</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{dateBR(x.date)}</td><td><span className={`finance-type ${x.type==="income"?"income":"expense"}`}>{x.type==="income"?"Entrada":"Saída"}</span></td><td>{categories[x.category]||x.category}</td><td>{x.description}</td><td>{methods[x.method]||x.method||"—"}</td><td><span className={`finance-amount ${x.type==="income"?"income":"expense"}`}>{x.type==="income"?"+":"−"} {brl(x.amount)}</span></td><td><button className="btn btn-gray" onClick={()=>{setEdit(x);setOpen(true)}}><Pencil size={15}/></button> <button className="btn btn-danger" onClick={()=>del(x.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!items.length&&<div style={{padding:20,color:"#64748b"}}>Nenhum lançamento.</div>}</div>
    {open&&<Transaction initial={edit||{type:"income",category:"taxa",description:"",amount:"",date:todayISO()}} close={()=>setOpen(false)} save={save}/>}</>;
}
function Transaction({initial,close,save}){let[f,setF]=useState(initial);const methods={pix:"Pix",cash:"Dinheiro",credit:"Cartão de crédito",debit:"Cartão de débito",transfer:"Transferência",other:"Outro"};return <Modal title={initial.id?"Editar lançamento":"Novo lançamento"} close={close}><F l="Tipo"><select className="input" value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="income">Entrada</option><option value="expense">Saída</option></select></F><F l="Forma de pagamento/recebimento"><select className="input" value={f.method||""} onChange={e=>setF({...f,method:e.target.value})}><option value="">Não informado</option>{Object.entries(methods).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></F><F l="Categoria"><select className="input" value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></F><F l="Descrição"><input className="input" value={f.description||""} onChange={e=>setF({...f,description:e.target.value})}/></F><F l="Valor"><input className="input" value={f.amount??""} onChange={e=>setF({...f,amount:e.target.value})}/></F><F l="Data"><input className="input" type="date" value={f.date||todayISO()} onChange={e=>setF({...f,date:e.target.value})}/></F><button className="btn btn-primary" style={{marginTop:5}} onClick={()=>save(f)}>Salvar</button></Modal>}
function Reports({data}){
  const now=currentMonth(), currentYear=now.slice(0,4);
  const years=Array.from(new Set([
    currentYear,
    ...(data.transactions||[]).map(x=>String(x.date||"").slice(0,4)).filter(Boolean),
    ...(data.residents||[]).map(x=>residentStartMonth(x).slice(0,4)).filter(Boolean),
    ...(data.bookings||[]).map(x=>bookingDate(x.date).slice(0,4)).filter(Boolean)
  ])).sort((a,b)=>Number(b)-Number(a));
  const [year,setYear]=useState(currentYear),[from,setFrom]=useState(`${currentYear}-01-01`),[to,setTo]=useState(`${currentYear}-12-31`),[mode,setMode]=useState("accounts");
  const inRange=d=>{const x=String(d||"").slice(0,10);return x>=from&&x<=to};
  const tx=(data.transactions||[]).filter(x=>inRange(x.date));
  const income=tx.filter(x=>x.type==="income").reduce((a,x)=>a+Number(x.amount||0),0);
  const expense=tx.filter(x=>x.type==="expense").reduce((a,x)=>a+Number(x.amount||0),0);
  const initialTx=(data.transactions||[]).filter(x=>String(x.date||"").slice(0,10)<from);
  const initial=initialTx.reduce((a,x)=>a+(x.type==="income"?1:-1)*Number(x.amount||0),0);
  const result=income-expense, final=initial+result;
  const monthsBetween=(a,b)=>{
    if(!a||!b||a>b)return[];
    const out=[];let[y,m]=a.split("-").map(Number),[ey,em]=b.split("-").map(Number);
    while(y<ey||(y===ey&&m<=em)){
      out.push(`${y}-${String(m).padStart(2,"0")}`);m++;
      if(m===13){m=1;y++}
    }
    return out;
  };
  const setPeriod=y=>{setYear(String(y));setFrom(`${y}-01-01`);setTo(`${y}-12-31`)};
  const periodStartMonth=from.slice(0,7), requestedEndMonth=to.slice(0,7), currentEnd=currentMonth();
  const effectiveEndMonth=requestedEndMonth>currentEnd?currentEnd:requestedEndMonth;
  const pendingMonthsAsOf=resident=>{
    if(resident?.exempt||resident?.inactive)return[];
    const start=residentStartMonth(resident);
    if(!start||start>effectiveEndMonth)return[];
    const paid=new Set((resident?.paidMonths||[]).map(String));
    return monthsBetween(start,effectiveEndMonth).filter(m=>!paid.has(m));
  };
  const fee=Number(data.settings?.taxaMensal||0);
  const monthlyReceivable=(data.residents||[]).filter(r=>!r.exempt&&!r.inactive).reduce((sum,r)=>sum+pendingMonthsAsOf(r).length*fee,0);
  const bookingReceivable=(data.bookings||[])
    .filter(b=>{const d=bookingDate(b.date).slice(0,10);return d>=from&&d<=to})
    .reduce((sum,b)=>{
      const total=Number(b.totalAmount||0);
      const received=(data.payments||[])
        .filter(p=>String(p.bookingId)===String(b.id)&&String(p.date||"").slice(0,10)<=to)
        .reduce((a,p)=>a+Number(p.amount||0),0);
      return sum+Math.max(0,total-received);
    },0);
  const receivable=monthlyReceivable+bookingReceivable;
  const monthRows=monthsBetween(periodStartMonth,effectiveEndMonth).map(m=>{
    const rows=tx.filter(x=>String(x.date||"").slice(0,7)===m);
    const inc=rows.filter(x=>x.type==="income").reduce((a,x)=>a+Number(x.amount||0),0);
    const out=rows.filter(x=>x.type==="expense").reduce((a,x)=>a+Number(x.amount||0),0);
    return{m,inc,out,net:inc-out};
  });
  const incomeByCat={},expenseByCat={};
  tx.forEach(x=>{
    const key=categories[x.category]||x.category||"Outras", amount=Number(x.amount||0);
    if(x.type==="income")incomeByCat[key]=(incomeByCat[key]||0)+amount;
    else expenseByCat[key]=(expenseByCat[key]||0)+amount;
  });
  const exportCSV=()=>{
    const rows=[
      ["AMVF2 - Associação de Moradores do Vila Floresta 2"],
      ["PRESTAÇÃO DE CONTAS"],
      [`Período: ${dateBR(from)} a ${dateBR(to)}`],[],
      ["RESUMO"],["Saldo inicial",initial],["Entradas",income],["Saídas",expense],["Resultado do período",result],["Saldo final",final],["A receber",receivable],[],
      ["MOVIMENTAÇÃO MENSAL"],["Mês","Entradas","Saídas","Resultado"]
    ];
    monthRows.forEach(r=>rows.push([monthLabel(r.m),r.inc,r.out,r.net]));
    rows.push([], ["RECEITAS POR CATEGORIA"],["Categoria","Valor"]);
    Object.entries(incomeByCat).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>rows.push([k,v]));
    rows.push([], ["DESPESAS POR CATEGORIA"],["Categoria","Valor"]);
    Object.entries(expenseByCat).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>rows.push([k,v]));
    rows.push([], ["LANÇAMENTOS DO PERÍODO"],["Data","Tipo","Categoria","Descrição","Forma","Valor"]);
    tx.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).forEach(x=>rows.push([x.date,x.type==="income"?"Entrada":"Saída",categories[x.category]||x.category,x.description||"",x.method||"",x.amount]));
    csvDownload(`prestacao_de_contas_${from}_${to}.csv`,rows);
  };
  const printTitle=mode==="accounts"?"Prestação de Contas":mode==="residents"?"Relatório de Moradores":mode==="history"?"Histórico Financeiro":"Auditoria";
  return <><Head t="Prestação de contas" s="Resumo financeiro para diretoria e assembleia" a={<div className="report-actions"><button className="btn btn-gray" onClick={exportCSV}><Download size={15}/> Exportar CSV</button><button className="btn btn-primary" onClick={()=>window.print()}><Printer size={15}/> Imprimir / PDF</button></div>}/>
    <div className="report-tabs no-print">
      <button className={`btn ${mode==="accounts"?"btn-primary":"btn-gray"}`} onClick={()=>setMode("accounts")}>Prestação de contas</button>
      <button className={`btn ${mode==="residents"?"btn-primary":"btn-gray"}`} onClick={()=>setMode("residents")}>Moradores</button>
      <button className={`btn ${mode==="history"?"btn-primary":"btn-gray"}`} onClick={()=>setMode("history")}>Histórico financeiro</button>
      <button className={`btn ${mode==="audit"?"btn-primary":"btn-gray"}`} onClick={()=>setMode("audit")}>Auditoria</button>
    </div>
    <div className="report-print-title"><h2>{printTitle}</h2><div>{dateBR(from)} a {dateBR(to)}</div></div>
    {mode==="accounts"&&<>
      <div className="card report-filters no-print"><div className="date-range"><F l="Ano"><select className="input" value={year} onChange={e=>setPeriod(e.target.value)}>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></F><F l="De"><input className="input" type="date" value={from} onChange={e=>{setFrom(e.target.value);setYear(e.target.value.slice(0,4))}}/></F><F l="Até"><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></F></div></div>
      <div className="report-summary"><Stat t="Saldo inicial" v={brl(initial)}/><Stat t="Entradas" v={brl(income)}/><Stat t="Saídas" v={brl(expense)}/><Stat t="Resultado do período" v={brl(result)}/><Stat t="Saldo final" v={brl(final)}/><Stat t="A receber" v={brl(receivable)}/></div>
      <div className="card report-section"><h3>Movimentação mensal</h3><div style={{overflow:"auto"}}><table><thead><tr><th>Mês</th><th>Entradas</th><th>Saídas</th><th>Resultado</th></tr></thead><tbody>{monthRows.map(r=><tr key={r.m}><td>{monthLabel(r.m)}</td><td className="positive">{brl(r.inc)}</td><td className="negative">{brl(r.out)}</td><td className={r.net>=0?"positive":"negative"}><b>{r.net>=0?"+":"−"} {brl(Math.abs(r.net))}</b></td></tr>)}</tbody></table></div></div>
      <div className="report-grid"><div className="card report-section"><h3>Receitas por categoria</h3>{Object.entries(incomeByCat).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div className="report-line" key={k}><span>{k}</span><b className="positive">{brl(v)}</b></div>)}{!Object.keys(incomeByCat).length&&<div className="empty-state">Nenhuma receita no período.</div>}</div><div className="card report-section"><h3>Despesas por categoria</h3>{Object.entries(expenseByCat).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div className="report-line" key={k}><span>{k}</span><b className="negative">{brl(v)}</b></div>)}{!Object.keys(expenseByCat).length&&<div className="empty-state">Nenhuma despesa no período.</div>}</div></div>
      <div className="card report-table" style={{padding:8,overflow:"auto",marginTop:16}}><h3 style={{padding:"0 10px"}}>Lançamentos do período</h3><table><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Forma</th><th>Valor</th></tr></thead><tbody>{tx.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(x=><tr key={x.id}><td>{dateBR(x.date)}</td><td>{x.type==="income"?"Entrada":"Saída"}</td><td>{categories[x.category]||x.category}</td><td>{x.description||"—"}</td><td>{x.method||"—"}</td><td className={x.type==="income"?"positive":"negative"}>{x.type==="income"?"+":"−"} {brl(x.amount)}</td></tr>)}</tbody></table>{!tx.length&&<div className="empty-state">Nenhum lançamento no período.</div>}</div>
    </>}
    {mode==="residents"&&<><div className="card report-filters no-print"><F l="Mês de referência"><input className="input" type="month" value={from.slice(0,7)} onChange={e=>{const x=e.target.value;setFrom(`${x}-01`);const d=new Date(Number(x.slice(0,4)),Number(x.slice(5,7)),0);setTo(`${x}-${String(d.getDate()).padStart(2,"0")}`)}}/></F></div><div className="report-summary"><Stat t="Moradores" v={(data.residents||[]).filter(x=>!x.inactive).length}/><Stat t="Pagos" v={(data.residents||[]).filter(x=>!x.inactive&&(x.exempt||(x.paidMonths||[]).includes(from.slice(0,7)))).length}/><Stat t="Pendentes" v={(data.residents||[]).filter(x=>!x.exempt&&!x.inactive&&residentPendingMonths(x).includes(from.slice(0,7))).length}/><Stat t="% recebido" v={`${(data.residents||[]).filter(x=>!x.inactive).length?Math.round((data.residents||[]).filter(x=>!x.inactive&&(x.exempt||(x.paidMonths||[]).includes(from.slice(0,7)))).length/(data.residents||[]).filter(x=>!x.inactive).length*100):0}%`}/></div><div className="card report-table" style={{padding:8,overflow:"auto"}}><table><thead><tr><th>Morador</th><th>Endereço</th><th>Meses pendentes</th><th>Valor em aberto</th></tr></thead><tbody>{(data.residents||[]).filter(x=>!x.inactive).map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.house||"—"}</td><td>{residentPendingMonths(x).length}</td><td>{brl(residentPendingMonths(x).length*Number(data.settings?.taxaMensal||0))}</td></tr>)}</tbody></table></div></>}
    {mode==="history"&&<div className="card report-table" style={{padding:8,overflow:"auto"}}><table><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Forma</th><th>Valor</th></tr></thead><tbody>{(data.transactions||[]).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=><tr key={x.id}><td>{dateBR(x.date)}</td><td>{x.type==="income"?"Entrada":"Saída"}</td><td>{categories[x.category]||x.category}</td><td>{x.description||"—"}</td><td>{x.method||"—"}</td><td>{brl(x.amount)}</td></tr>)}</tbody></table></div>}
    {mode==="audit"&&<div className="card report-table" style={{padding:8,overflow:"auto"}}><div style={{padding:"10px 10px 0"}}><h3>Histórico de alterações</h3><p style={{color:"#64748b",fontSize:13}}>Registros de quem fez a operação e quando. O responsável é definido em Configurações.</p></div><table><thead><tr><th>Data</th><th>Responsável</th><th>Ação</th><th>Descrição</th><th>Valor</th></tr></thead><tbody>{(data.audit||[]).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=><tr key={x.id}><td>{new Date(x.date).toLocaleString("pt-BR")}</td><td>{x.actor||"Diretoria"}</td><td>{x.action}</td><td>{x.description}</td><td>{Number(x.amount||0)?brl(x.amount):"—"}</td></tr>)}</tbody></table>{!(data.audit||[]).length&&<div className="empty-state">Ainda não há registros de auditoria.</div>}</div>}
  </>;
}

function Meetings({data,refresh}){
  const [filter,setFilter]=useState("all"),[q,setQ]=useState(""),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[detail,setDetail]=useState(null);
  const meetings=data.meetings||[];
  const today=todayISO();
  const typeLabel={meeting:"Reunião",assembly:"Assembleia geral",extraordinary:"Assembleia extraordinária"};
  const statusLabel={scheduled:"Agendada",held:"Realizada",cancelled:"Cancelada"};
  const statusClass={scheduled:"badge-green",held:"badge-gray",cancelled:"badge-red"};
  const visible=meetings.filter(x=>{
    const term=`${x.title||""} ${x.location||""} ${x.agenda||""} ${x.type||""} ${x.status||""}`.toLowerCase();
    if(q&&!term.includes(q.toLowerCase()))return false;
    if(filter!=="all"&&String(x.status||"scheduled")!==filter)return false;
    return true;
  }).sort((a,b)=>`${String(b.date||"")} ${String(b.time||"")}`.localeCompare(`${String(a.date||"")} ${String(a.time||"")}`));
  const openNew=()=>{setEdit(null);setOpen(true)};
  const save=async f=>{
    if(!f.title?.trim())return alert("Informe o título da reunião ou assembleia.");
    if(!f.date)return alert("Informe a data.");
    const o={...f,title:String(f.title).trim(),date:String(f.date),time:String(f.time||""),location:String(f.location||""),agenda:String(f.agenda||""),participants:String(f.participants||""),decisions:String(f.decisions||""),notes:String(f.notes||""),type:f.type||"meeting",status:f.status||"scheduled",created_date:edit?.created_date||new Date().toISOString()};
    const r=await safe(()=>edit?update("Meetings",edit.id,o):create("Meetings",{...o,id:uid()}));
    if(!r)return;
    saveCache({...data,meetings:edit?meetings.map(x=>x.id===edit.id?r:x):[r,...meetings]});
    setOpen(false);setEdit(null);setDetail(r);await refresh();
  };
  const del=async id=>{if(!confirm("Excluir esta reunião/assembleia?"))return;const r=await safe(()=>remove("Meetings",id));if(!r)return;saveCache({...data,meetings:meetings.filter(x=>x.id!==id)});setDetail(null);await refresh()};
  const upcoming=visible.filter(x=>String(x.date||"")>=today&&String(x.status||"scheduled")!=="cancelled");
  const past=visible.filter(x=>!(String(x.date||"")>=today&&String(x.status||"scheduled")!=="cancelled"));
  return <><Head t="Reuniões e Assembleias" s="Agenda, pauta e registro das deliberações da associação" a={<button className="btn btn-primary" onClick={openNew}><Plus size={16}/> Nova reunião</button>}/>
    <div className="card meetings-toolbar no-print"><div className="meetings-search"><Search size={17}/><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por título, local ou pauta"/></div><div className="report-tabs" style={{margin:0}}><button className={`btn ${filter==="all"?"btn-primary":"btn-gray"}`} onClick={()=>setFilter("all")}>Todas</button><button className={`btn ${filter==="scheduled"?"btn-primary":"btn-gray"}`} onClick={()=>setFilter("scheduled")}>Agendadas</button><button className={`btn ${filter==="held"?"btn-primary":"btn-gray"}`} onClick={()=>setFilter("held")}>Realizadas</button><button className={`btn ${filter==="cancelled"?"btn-primary":"btn-gray"}`} onClick={()=>setFilter("cancelled")}>Canceladas</button></div></div>
    {upcoming.length>0&&<section className="meetings-section"><div className="meetings-section-head"><h3>Próximas</h3><span className="badge badge-green">{upcoming.length}</span></div><div className="meetings-grid">{upcoming.map(x=><MeetingCard key={x.id} x={x} typeLabel={typeLabel} statusLabel={statusLabel} statusClass={statusClass} onClick={()=>setDetail(x)}/>)}</div></section>}
    <section className="meetings-section"><div className="meetings-section-head"><h3>{upcoming.length?"Histórico":"Reuniões registradas"}</h3><span className="badge badge-gray">{past.length}</span></div>{past.length?<div className="meetings-grid">{past.map(x=><MeetingCard key={x.id} x={x} typeLabel={typeLabel} statusLabel={statusLabel} statusClass={statusClass} onClick={()=>setDetail(x)}/>)}</div>:<div className="card empty-state">Nenhuma reunião encontrada.</div>}</section>
    {open&&<MeetingForm initial={edit||{type:"meeting",status:"scheduled",date:todayISO()}} close={()=>{setOpen(false);setEdit(null)}} save={save}/>} 
    {detail&&<MeetingDetail x={detail} typeLabel={typeLabel} statusLabel={statusLabel} statusClass={statusClass} close={()=>setDetail(null)} edit={()=>{setEdit(detail);setDetail(null);setOpen(true)}} del={()=>del(detail.id)}/>} 
  </>;
}
function MeetingCard({x,typeLabel,statusLabel,statusClass,onClick}){return <button className="meeting-card card" onClick={onClick}><div className="meeting-card-date"><strong>{String(x.date||"").slice(8,10)}</strong><span>{String(x.date||"").slice(5,7)==="01"?"JAN":String(x.date||"").slice(5,7)==="02"?"FEV":String(x.date||"").slice(5,7)==="03"?"MAR":String(x.date||"").slice(5,7)==="04"?"ABR":String(x.date||"").slice(5,7)==="05"?"MAI":String(x.date||"").slice(5,7)==="06"?"JUN":String(x.date||"").slice(5,7)==="07"?"JUL":String(x.date||"").slice(5,7)==="08"?"AGO":String(x.date||"").slice(5,7)==="09"?"SET":String(x.date||"").slice(5,7)==="10"?"OUT":String(x.date||"").slice(5,7)==="11"?"NOV":"DEZ"}</span></div><div className="meeting-card-body"><div className="meeting-card-top"><span className="meeting-type">{typeLabel[x.type]||x.type||"Reunião"}</span><span className={`badge ${statusClass[x.status]||"badge-gray"}`}>{statusLabel[x.status]||"Agendada"}</span></div><b>{x.title||"Reunião sem título"}</b><div className="meeting-meta"><span>{dateBR(x.date)}{x.time?` · ${x.time}`:""}</span>{x.location&&<span>{x.location}</span>}</div>{x.agenda&&<p>{String(x.agenda).slice(0,130)}{String(x.agenda).length>130?"…":""}</p>}</div></button>}
function MeetingForm({initial,close,save}){const [f,setF]=useState(initial);return <Modal title={initial.id?"Editar reunião / assembleia":"Nova reunião / assembleia"} close={close}><F l="Tipo"><select className="input" value={f.type||"meeting"} onChange={e=>setF({...f,type:e.target.value})}><option value="meeting">Reunião</option><option value="assembly">Assembleia geral</option><option value="extraordinary">Assembleia extraordinária</option></select></F><F l="Título *"><input className="input" autoFocus value={f.title||""} onChange={e=>setF({...f,title:e.target.value})} placeholder="Ex.: Reunião da diretoria"/></F><div className="date-range"><F l="Data *"><input className="input" type="date" value={f.date||""} onChange={e=>setF({...f,date:e.target.value})}/></F><F l="Horário"><input className="input" type="time" value={f.time||""} onChange={e=>setF({...f,time:e.target.value})}/></F></div><F l="Local"><input className="input" value={f.location||""} onChange={e=>setF({...f,location:e.target.value})} placeholder="Salão comunitário, sede, etc."/></F><F l="Pauta"><textarea className="input" rows="4" value={f.agenda||""} onChange={e=>setF({...f,agenda:e.target.value})} placeholder="Assuntos a serem discutidos"/></F><F l="Participantes"><textarea className="input" rows="3" value={f.participants||""} onChange={e=>setF({...f,participants:e.target.value})} placeholder="Nomes ou lista de participantes"/></F><F l="Decisões / deliberações"><textarea className="input" rows="4" value={f.decisions||""} onChange={e=>setF({...f,decisions:e.target.value})} placeholder="Registre as decisões tomadas"/></F><F l="Status"><select className="input" value={f.status||"scheduled"} onChange={e=>setF({...f,status:e.target.value})}><option value="scheduled">Agendada</option><option value="held">Realizada</option><option value="cancelled">Cancelada</option></select></F><F l="Observações"><textarea className="input" rows="3" value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/></F><button className="btn btn-primary" onClick={()=>save(f)}>Salvar</button></Modal>}
function MeetingDetail({x,typeLabel,statusLabel,statusClass,close,edit,del}){return <Modal title={x.title||"Reunião / Assembleia"} close={close}><div className="meeting-detail-head"><span className="meeting-type">{typeLabel[x.type]||x.type||"Reunião"}</span><span className={`badge ${statusClass[x.status]||"badge-gray"}`}>{statusLabel[x.status]||"Agendada"}</span></div><div className="profile-details meeting-details"><span><b>Data</b>{dateBR(x.date)}</span><span><b>Horário</b>{x.time||"Não informado"}</span><span><b>Local</b>{x.location||"Não informado"}</span></div><div className="profile-section"><h3>Pauta</h3><div className="meeting-text">{x.agenda||"Nenhuma pauta registrada."}</div></div><div className="profile-section"><h3>Participantes</h3><div className="meeting-text">{x.participants||"Nenhum participante registrado."}</div></div><div className="profile-section"><h3>Decisões / deliberações</h3><div className="meeting-text">{x.decisions||"Nenhuma decisão registrada."}</div></div>{x.notes&&<div className="profile-section"><h3>Observações</h3><div className="meeting-text">{x.notes}</div></div>}<div className="profile-actions no-print"><button className="btn btn-primary" onClick={()=>printMeetingMinutes(x)}><Printer size={15}/> Imprimir / PDF da ata</button><button className="btn btn-gray" onClick={edit}><Pencil size={15}/> Editar</button><button className="btn btn-danger" onClick={del}><Trash2 size={15}/> Excluir</button></div></Modal>}
function printMeetingMinutes(x){const title=String(x.title||"Reunião / Assembleia"),esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");const type=x.type==="assembly"?"Assembleia geral":x.type==="extraordinary"?"Assembleia extraordinária":"Reunião";const w=window.open("","_blank","width=850,height=950");if(!w){alert("O navegador bloqueou a janela. Permita pop-ups para imprimir a ata.");return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Ata — ${esc(title)}</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#111;max-width:900px;margin:auto;line-height:1.5}.top{text-align:center;border-bottom:2px solid #111;padding-bottom:14px;margin-bottom:22px}.top h1{font-size:20px;margin:0}.top p{margin:4px 0;color:#555}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:20px}.box{border:1px solid #ddd;border-radius:7px;padding:10px}.box b{display:block;font-size:11px;text-transform:uppercase;color:#666;margin-bottom:3px}.section{margin-top:18px}.section h2{font-size:15px;margin:0 0 7px;border-bottom:1px solid #ddd;padding-bottom:4px}.text{white-space:pre-wrap;min-height:32px}.sign{display:grid;grid-template-columns:1fr 1fr;gap:70px;margin-top:70px}.line{border-top:1px solid #111;padding-top:6px;text-align:center}.foot{text-align:center;margin-top:30px;font-size:11px;color:#666}@media(max-width:600px){body{padding:16px}.meta,.sign{grid-template-columns:1fr}.sign{gap:45px;margin-top:40px}}@media print{@page{size:A4 portrait;margin:15mm}body{padding:0}}</style></head><body><div class="top"><h1>Associação de Moradores do Vila Floresta 2</h1><p>AMVF2 — Registro de ${esc(type)}</p></div><h2>${esc(title)}</h2><div class="meta"><div class="box"><b>Data</b>${esc(dateBR(x.date))}</div><div class="box"><b>Horário</b>${esc(x.time||"Não informado")}</div><div class="box"><b>Local</b>${esc(x.location||"Não informado")}</div><div class="box"><b>Status</b>${esc(x.status==="held"?"Realizada":x.status==="cancelled"?"Cancelada":"Agendada")}</div></div><div class="section"><h2>Pauta</h2><div class="text">${esc(x.agenda||"Não registrada")}</div></div><div class="section"><h2>Participantes</h2><div class="text">${esc(x.participants||"Não registrados")}</div></div><div class="section"><h2>Decisões / deliberações</h2><div class="text">${esc(x.decisions||"Não registradas")}</div></div>${x.notes?`<div class="section"><h2>Observações</h2><div class="text">${esc(x.notes)}</div></div>`:""}<div class="sign"><div class="line">Presidente / responsável</div><div class="line">Secretário(a)</div></div><div class="foot">Documento gerado pelo sistema administrativo da AMVF2.</div><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);w.document.close()}

function Delinquency({data}){
  const fee=Number(data.settings?.taxaMensal||0),r=(data.residents||[]).filter(x=>!x.exempt&&!x.inactive),items=r.map(x=>({...x,pendingMonths:residentPendingMonths(x)})).filter(x=>x.pendingMonths.length).sort((a,b)=>b.pendingMonths.length-a.pendingMonths.length||String(a.name).localeCompare(String(b.name))), total=items.reduce((a,x)=>a+x.pendingMonths.length*fee,0), one=items.filter(x=>x.pendingMonths.length===1).length,two=items.filter(x=>x.pendingMonths.length===2).length,three=items.filter(x=>x.pendingMonths.length>=3).length;
  return <><Head t="Controle de inadimplência" s="Acompanhamento das mensalidades em aberto"/><div className="report-summary"><Stat t="Total em aberto" v={brl(total)}/><Stat t="1 mês atrasado" v={one}/><Stat t="2 meses atrasados" v={two}/><Stat t="3+ meses atrasados" v={three}/></div><div className="card delinquency-summary"><div><b>Critério</b><span>Mensalidades do ano até {monthLabel(currentMonth())}. Isentos não entram na cobrança.</span></div><div><b>{items.length}</b><span>moradores com pendência</span></div></div><div className="card report-table" style={{padding:8,overflow:"auto"}}><table><thead><tr><th>Morador</th><th>Endereço</th><th>Meses pendentes</th><th>Valor</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.house||"—"}</td><td><div className="month-chips">{x.pendingMonths.map(m=><span key={m}>{monthLabel(m).split(" de ")[0]}</span>)}</div></td><td><b className="negative">{brl(x.pendingMonths.length*fee)}</b></td></tr>)}</tbody></table>{!items.length&&<div className="empty-state">Excelente: não há mensalidades em aberto.</div>}</div></>;
}
function Bookings({data,refresh}){
  const [cursor,setCursor]=useState(todayISO().slice(0,7)),[selected,setSelected]=useState(todayISO()),[view,setView]=useState("month"),[edit,setEdit]=useState(null),[open,setOpen]=useState(false),[detail,setDetail]=useState(null),[paymentOpen,setPaymentOpen]=useState(false);
  const bookings=data.bookings||[], payments=data.payments||[];
  const monthDays=useMemo(()=>{const[y,m]=cursor.split("-").map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0),firstDay=(first.getDay()+6)%7,total=Math.ceil((firstDay+last.getDate())/7)*7;return Array.from({length:total},(_,i)=>{const n=i-firstDay+1;if(n<1||n>last.getDate())return null;return `${y}-${String(m).padStart(2,"0")}-${String(n).padStart(2,"0")}`})},[cursor]);
  const normalized=useMemo(()=>bookings.map(x=>({...x,_calendarDate:bookingDate(x.date)})),[bookings]);
  const monthBookings=useMemo(()=>normalized.filter(x=>x._calendarDate.startsWith(cursor)).sort((a,b)=>String(a.timeSlot||"").localeCompare(String(b.timeSlot||""))),[normalized,cursor]);
  const selectedBookings=useMemo(()=>normalized.filter(x=>x._calendarDate===selected).sort((a,b)=>String(a.timeSlot||"").localeCompare(String(b.timeSlot||""))),[normalized,selected]);
  const paymentTotal=id=>payments.filter(p=>String(p.bookingId)===String(id)).reduce((a,p)=>a+Number(p.amount||0),0);
  const balance=x=>Math.max(0,Number(x.totalAmount||0)-paymentTotal(x.id));
  const methods={pix:"Pix",cash:"Dinheiro",credit:"Cartão de crédito",debit:"Cartão de débito",transfer:"Transferência",other:"Outro"};
  const changeMonth=d=>{const[y,m]=cursor.split("-").map(Number),n=new Date(y,m-1+d,1);setCursor(`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,"0")}`)};
  const goToday=()=>{const t=todayISO();setCursor(t.slice(0,7));setSelected(t)};
  const openNew=(date=selected,time=slots[0])=>{const day=bookingDate(date),occupied=bookings.filter(x=>bookingDate(x.date)===day).map(x=>String(x.timeSlot||"")),firstFree=time&&!occupied.includes(time)?time:slots.find(s=>!occupied.includes(s))||"";if(!firstFree){alert(`A sala comunitária já está ocupada em todos os horários de ${dateBR(day)}.`);return}setEdit(null);setOpen(true);setNewBookingDate(day);setNewBookingTime(firstFree)};
  const [newBookingDate,setNewBookingDate]=useState(todayISO()),[newBookingTime,setNewBookingTime]=useState(slots[0]);
  const save=async f=>{const normalizedDate=bookingDate(f.date),conflict=bookings.find(x=>String(x.id)!==String(edit?.id||"")&&bookingDate(x.date)===normalizedDate&&String(x.timeSlot||"")===String(f.timeSlot||""));if(conflict){alert(`Este horário já está reservado para a sala comunitária.\n\nData: ${dateBR(normalizedDate)}\nHorário: ${f.timeSlot}`);return}const o={...f,date:normalizedDate,totalAmount:parseMoney(f.totalAmount),created_date:edit?.created_date||new Date().toISOString(),status:f.status||"pending",residentId:String(f.residentId||"")};const r=await safe(()=>edit?update("Bookings",edit.id,o):create("Bookings",{...o,id:uid()}));if(!r)return;saveCache({...data,bookings:edit?data.bookings.map(x=>x.id===edit.id?r:x):[r,...data.bookings]});setOpen(false);setEdit(null);setDetail(r);setSelected(bookingDate(r.date));setCursor(bookingDate(r.date).slice(0,7));await refresh()};
  const del=async id=>{if(!confirm("Excluir este agendamento? Os recebimentos vinculados também serão excluídos."))return;const linked=payments.filter(p=>String(p.bookingId)===String(id));for(const p of linked){const rr=await safe(()=>remove("Payments",p.id));if(!rr)return}const r=await safe(()=>remove("Bookings",id));if(!r)return;saveCache({...data,bookings:data.bookings.filter(x=>x.id!==id),payments:data.payments.filter(p=>String(p.bookingId)!==String(id))});setDetail(null);await refresh()};
  const openEdit=x=>{setEdit(x);setSelected(bookingDate(x.date));setCursor(bookingDate(x.date).slice(0,7));setOpen(true)};
  const registerPayment=async f=>{const r=await safe(()=>create("Payments",{...f,id:uid(),bookingId:detail.id,residentId:detail.residentId||"",amount:parseMoney(f.amount)}));if(!r)return;saveCache({...data,payments:[r,...(data.payments||[])]});setPaymentOpen(false);await refresh()};
  const clickBooking=x=>setDetail(x);
  const paymentStatus=x=>{const total=Number(x.totalAmount||0),got=paymentTotal(x.id);return total<=0?"Sem valor":got<=0?"Pendente":got+0.009>=total?"Pago":"Parcial"};
  const statusBadge=x=>paymentStatus(x)==="Pago"?"badge-green":paymentStatus(x)==="Parcial"?"badge-yellow":"badge-gray";
  return <><Head t="Agendamentos" s="Calendário da sala comunitária" a={<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn btn-gray" onClick={goToday}>Hoje</button><button className="btn btn-primary" onClick={()=>openNew()}><Plus/> Novo agendamento</button></div>}/>
    <div className="calendar-toolbar card"><div className="calendar-title"><button className="btn btn-gray icon-btn" onClick={()=>changeMonth(-1)}><ChevronLeft/></button><h2>{monthLabel(cursor)}</h2><button className="btn btn-gray icon-btn" onClick={()=>changeMonth(1)}><ChevronRight/></button></div><div style={{display:"flex",gap:6}}><button className={`btn ${view==="month"?"btn-primary":"btn-gray"}`} onClick={()=>setView("month")}>Mês</button><button className={`btn ${view==="day"?"btn-primary":"btn-gray"}`} onClick={()=>setView("day")}>Dia</button></div></div>
    {view==="month"?<div className="calendar-layout"><div className="card calendar-grid"><div className="calendar-weekdays">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(x=><div key={x}>{x}</div>)}</div><div className="calendar-cells">{monthDays.map((date,i)=>{if(!date)return <div key={i} className="calendar-cell empty"/>;const items=monthBookings.filter(x=>x._calendarDate===date);return <div key={date} className={`calendar-cell ${selected===date?"selected":""}`} onClick={()=>{setSelected(date);setDetail(null)}}><div className="calendar-cell-head"><b>{Number(date.slice(-2))}</b><button className="day-add" onClick={e=>{e.stopPropagation();openNew(date)}}>+</button></div>{items.map(x=><button key={x.id} className="calendar-event" onClick={e=>{e.stopPropagation();clickBooking(x)}}><span>{x.timeSlot}</span><b>{x.residentName||"Sem nome"}</b><small className={`badge ${statusBadge(x)}`}>{paymentStatus(x)}</small></button>)}</div>})}</div></div><aside className="card calendar-detail"><div className="calendar-detail-head"><div><b>Agendamentos</b><div>{dateBR(selected)}</div></div><button className="btn btn-primary" onClick={()=>openNew(selected)}><Plus size={15}/> Agendar</button></div>{selectedBookings.length?selectedBookings.map(x=><div key={x.id} className="booking-detail-item" onClick={()=>clickBooking(x)} style={{cursor:"pointer"}}><div className="booking-time">{x.timeSlot}</div><div className="booking-main"><b>{x.residentName||"Sem nome"}</b>{x.purpose&&<span>{x.purpose}</span>}<small>{brl(x.totalAmount||0)} · {paymentStatus(x)}</small></div></div>):<div style={{padding:15,color:"#64748b"}}>Nenhum agendamento neste dia.</div>}</aside></div>:<div className="card day-agenda"><div className="day-agenda-head"><h3>{dateBR(selected)}</h3><button className="btn btn-primary" onClick={()=>openNew(selected)}><Plus/> Novo</button></div>{slots.map(s=>{const items=selectedBookings.filter(x=>x.timeSlot===s);return <div className="day-slot" key={s}><div className="day-slot-time">{s}</div><div className="day-slot-content">{items.length?items.map(x=><div key={x.id} className="day-booking" onClick={()=>clickBooking(x)} style={{cursor:"pointer"}}><div><b>{x.residentName||"Sem nome"}</b>{x.purpose&&<span>{x.purpose}</span>}</div><div className="booking-actions"><span className={`badge ${statusBadge(x)}`}>{paymentStatus(x)}</span></div></div>):<button className="day-slot-free" onClick={()=>openNew(selected,s)}>Livre — clique para agendar</button>}</div></div>})}</div>}
    {open&&<Booking residents={data.residents||[]} initial={edit||{residentId:"",residentName:"",contact:"",purpose:"",date:newBookingDate,timeSlot:newBookingTime,status:"pending",totalAmount:""}} close={()=>{setOpen(false);setEdit(null)}} save={save}/>} 
    {detail&&<Modal title="Detalhes da reserva" close={()=>setDetail(null)}><div style={{display:"grid",gap:10}}><div><b>{detail.residentName||"Reserva avulsa"}</b><div style={{color:"#64748b"}}>{detail.residentId?"Morador/Associado":"Reserva avulsa"}</div></div><div><b>Data e horário</b><div>{dateBR(bookingDate(detail.date))} · {detail.timeSlot}</div></div>{detail.contact&&<div><b>Contato</b><div>{detail.contact}</div></div>}{detail.purpose&&<div><b>Finalidade</b><div>{detail.purpose}</div></div>}<div style={{padding:14,background:"#f8fafc",borderRadius:12}}><b>Financeiro</b><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:8}}><div><small>Total</small><div><b>{brl(detail.totalAmount||0)}</b></div></div><div><small>Recebido</small><div><b>{brl(paymentTotal(detail.id))}</b></div></div><div><small>A receber</small><div><b>{brl(balance(detail))}</b></div></div></div></div><div><b>Recebimentos</b>{payments.filter(p=>String(p.bookingId)===String(detail.id)).length?payments.filter(p=>String(p.bookingId)===String(detail.id)).map(p=><div key={p.id} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid #e2e8f0"}}><span>{dateBR(p.date)} · {methods[p.method]||p.method}</span><b>{brl(p.amount)}</b></div>):<div style={{color:"#64748b",padding:"8px 0"}}>Nenhum pagamento.</div>}</div><div style={{display:"flex",gap:8,justifyContent:"flex-end",flexWrap:"wrap"}}><button className="btn btn-primary" onClick={()=>setPaymentOpen(true)}>💰 Registrar pagamento</button><button className="btn btn-gray" onClick={()=>{setDetail(null);openEdit(detail)}}><Pencil size={15}/> Editar</button><button className="btn btn-danger" onClick={()=>del(detail.id)}><Trash2 size={15}/> Excluir</button></div></div></Modal>}
    {paymentOpen&&<PaymentForm booking={detail} remaining={balance(detail)} close={()=>setPaymentOpen(false)} save={registerPayment}/>}</>;
}
function Booking({initial,close,save,residents}){let[f,setF]=useState(initial);const ordered=(residents||[]).slice().sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")));const chooseResident=id=>{if(!id){setF(v=>({...v,residentId:"",residentName:"",contact:""}));return}const r=ordered.find(x=>String(x.id)===String(id));if(r)setF(v=>({...v,residentId:String(r.id),residentName:r.name||"",contact:r.phone||""}))};return <Modal title={initial.id?"Editar agendamento":"Novo agendamento"} close={close}><F l="Tipo de reserva"><select className="input" value={f.residentId?String(f.residentId):""} onChange={e=>chooseResident(e.target.value)}><option value="">Reserva avulsa</option>{ordered.map(r=><option key={r.id} value={r.id}>{r.name}{r.house?` — Endereço ${r.house}`:""}</option>)}</select></F><F l={f.residentId?"Morador/Associado":"Nome do responsável *"}><input className="input" value={f.residentName||""} onChange={e=>setF({...f,residentName:e.target.value})}/></F><F l="Contato"><input className="input" value={f.contact||""} onChange={e=>setF({...f,contact:e.target.value})}/></F><F l="Finalidade"><input className="input" value={f.purpose||""} onChange={e=>setF({...f,purpose:e.target.value})}/></F><F l="Data"><input className="input" type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></F><F l="Horário"><select className="input" value={f.timeSlot} onChange={e=>setF({...f,timeSlot:e.target.value})}>{slots.map(s=><option key={s}>{s}</option>)}</select></F><F l="Valor total"><input className="input" inputMode="decimal" placeholder="R$ 0,00" value={f.totalAmount??""} onChange={e=>setF({...f,totalAmount:e.target.value})}/></F><F l="Status"><select className="input" value={f.status||"pending"} onChange={e=>setF({...f,status:e.target.value})}><option value="pending">Pendente</option><option value="booked">Confirmado</option></select></F><div style={{fontSize:12,color:"#64748b",marginBottom:12}}>O valor total será usado para calcular recebido, parcial e saldo a receber.</div><button className="btn btn-primary" onClick={()=>save(f)}>Salvar</button></Modal>}
function PaymentForm({booking,remaining,close,save}){const[f,setF]=useState({amount:remaining,date:todayISO(),method:"pix",description:""});return <Modal title="Registrar pagamento" close={close}><div style={{marginBottom:14,color:"#475569"}}>Reserva de <b>{booking.residentName||"Reserva avulsa"}</b><br/>Saldo atual: <b>{brl(remaining)}</b></div><F l="Valor recebido"><input className="input" inputMode="decimal" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></F><F l="Forma de pagamento"><select className="input" value={f.method} onChange={e=>setF({...f,method:e.target.value})}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit">Cartão de crédito</option><option value="debit">Cartão de débito</option><option value="transfer">Transferência</option><option value="other">Outro</option></select></F><F l="Data"><input className="input" type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></F><F l="Observação"><input className="input" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></F><button className="btn btn-primary" onClick={()=>save(f)}>Registrar pagamento</button></Modal>}
function Residents({data,refresh,setData}){
  const [m,setM]=useState(currentMonth()),[q,setQ]=useState(""),[edit,setEdit]=useState(null),[open,setOpen]=useState(false),[paying,setPaying]=useState(null),[savingMonth,setSavingMonth]=useState(""),[profile,setProfile]=useState(null);
  const r=(data.residents||[]).filter(x=>String(x.name).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
  const save=async f=>{if(!f.name?.trim()){alert("Informe o nome.");return}const o={...f,name:f.name.trim(),exempt:!!f.exempt,paidMonths:f.paidMonths||[],monthlyPaymentIds:f.monthlyPaymentIds||{},created_date:edit?.created_date||new Date().toISOString()};const x=await safe(()=>edit?update("Residents",edit.id,o):create("Residents",{...o,id:uid()}));if(!x)return;const saved=x.__writeAccepted?{...o,id:edit?.id||o.id}:x;saveCache({...data,residents:edit?data.residents.map(y=>y.id===edit.id?saved:y):[saved,...data.residents]});setOpen(false);await refresh()};
  const del=async id=>{if(!confirm("Excluir este morador?"))return;const x=await safe(()=>remove("Residents",id));if(!x)return;saveCache({...data,residents:data.residents.filter(y=>y.id!==id)});refresh()};
  const finishPayment=f=>{if(!paying)return;const resident=paying,referenceMonth=m,key=`${resident.id}|${referenceMonth}`;if(savingMonth)return;setSavingMonth(key);setPaying(null);(async()=>{const localTxId=uid(),y=await safe(()=>togglePayment(resident.id,referenceMonth,true,f.method,f.date,f.amount));if(!y){setSavingMonth("");refresh();return}const base={...resident},paidMonths=[...new Set([...(base.paidMonths||[]).map(String),referenceMonth])],monthlyPaymentIds={...(base.monthlyPaymentIds||{}),[referenceMonth]:y.transaction?.id||localTxId},localResident={...base,paidMonths,monthlyPaymentIds},localTx=y.transaction||{id:localTxId,type:"income",category:"taxa",description:String(resident.name||"Morador"),amount:Number(parseMoney(f.amount)||0),date:f.date,method:f.method,created_date:new Date().toISOString()},n={...data,residents:data.residents.map(z=>z.id===resident.id?localResident:z),transactions:data.transactions.some(t=>String(t.id)===String(localTx.id))?data.transactions:[localTx,...data.transactions]};saveCache(n);setSavingMonth("");setData(n);setTimeout(()=>refresh().catch(()=>{}),400)})()};
  const toggle=async x=>{if(x.exempt)return;const isPaid=(x.paidMonths||[]).includes(m),key=`${x.id}|${m}`;if(!isPaid){if(savingMonth===key)return;setPaying({...x,_monthlyFee:Number(data.settings?.taxaMensal||0)});return}if(savingMonth===key)return;if(!confirm(`Estornar a mensalidade de ${x.name} referente a ${monthLabel(m)}?`))return;setSavingMonth(key);const y=await safe(()=>togglePayment(x.id,m,false));if(!y){setSavingMonth("");return}const current=data.residents.find(z=>z.id===x.id)||x,linkedId=String(current.monthlyPaymentIds?.[m]||""),paidMonths=(current.paidMonths||[]).map(String).filter(v=>v!==m),monthlyPaymentIds={...(current.monthlyPaymentIds||{})};delete monthlyPaymentIds[m];const transactions=(data.transactions||[]).filter(t=>String(t.id)!==linkedId),n={...data,residents:data.residents.map(z=>z.id===x.id?{...current,paidMonths,monthlyPaymentIds}:z),transactions};saveCache(n);setData(n);setSavingMonth("");setTimeout(()=>refresh().catch(()=>{}),400)};
  return <><Head t="Moradores" s="Cadastro, mensalidades e ficha financeira" a={<button className="btn btn-primary" onClick={()=>{setEdit(null);setOpen(true)}}><Plus/> Novo morador</button>}/><div className="residents-toolbar"><button className="btn btn-gray" onClick={()=>setM(previousMonth(m))}><ChevronLeft size={15}/></button><input className="input" style={{maxWidth:180}} type="month" value={m} onChange={e=>setM(e.target.value)}/><button className="btn btn-gray" onClick={()=>setM(nextMonth(m))}><ChevronRight size={15}/></button><input className="input" style={{maxWidth:300}} placeholder="Buscar nome..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="admin-stats compact"><Stat t="Total" v={r.length}/><Stat t="Pagos" v={r.filter(x=>x.exempt||(x.paidMonths||[]).includes(m)).length}/><Stat t="Pendentes" v={r.filter(x=>!x.exempt&&!(x.paidMonths||[]).includes(m)).length}/><Stat t="Arrecadado" v={brl(r.filter(x=>!x.exempt&&(x.paidMonths||[]).includes(m)).length*Number(data.settings?.taxaMensal||0))}/></div><div className="card" style={{padding:8,overflow:"auto"}}><table><thead><tr><th>Morador</th><th>Endereço</th><th>Telefone</th><th>Status {monthLabel(m)}</th><th>Ações</th></tr></thead><tbody>{r.map(x=><tr key={x.id}><td><button className="resident-name-btn" onClick={()=>setProfile(x)}><UserRound size={15}/><span><b>{x.name}</b><small>Abrir ficha</small></span></button></td><td>{x.house||"—"}</td><td>{x.phone||"—"}</td><td>{x.exempt?<span className="badge badge-gray">Isento</span>:<button className={`badge ${savingMonth===`${x.id}|${m}`?"badge-gray":x.paidMonths?.includes(m)?"badge-green":"badge-yellow"}`} style={{border:0,opacity:savingMonth===`${x.id}|${m}`?0.75:1,cursor:"pointer"}} disabled={savingMonth===`${x.id}|${m}`} onClick={()=>toggle(x)}>{savingMonth===`${x.id}|${m}`?"Salvando...":x.paidMonths?.includes(m)?"Pago":"Pendente"}</button>}</td><td><button className="btn btn-gray" onClick={()=>{setEdit(x);setOpen(true)}}><Pencil size={15}/></button> <button className="btn btn-danger" onClick={()=>del(x.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!r.length&&<div className="empty-state">Nenhum morador cadastrado.</div>}</div>{open&&<Resident initial={edit||{name:"",house:"",phone:"",email:"",notes:"",exempt:false,paidMonths:[],monthlyPaymentIds:{}}} close={()=>setOpen(false)} save={save}/>} {paying&&<MonthlyPayment resident={paying} month={m} close={()=>setPaying(null)} save={finishPayment}/>} {profile&&<ResidentProfile data={data} resident={profile} close={()=>setProfile(null)}/>}</>;
}
function printReceipt({data,resident,payment,referenceMonth}){
  const association=data.settings?.associacao||"Associação de Moradores do Vila Floresta 2";
  const methods={pix:"Pix",cash:"Dinheiro",credit:"Cartão de crédito",debit:"Cartão de débito",transfer:"Transferência",other:"Outro"};
  const w=window.open("","_blank","width=760,height=900");
  if(!w){alert("O navegador bloqueou a janela do recibo. Permita pop-ups para imprimir o recibo.");return}
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Recibo AMVF2</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#111;max-width:760px;margin:auto}.box{border:1px solid #ddd;border-radius:12px;padding:28px}.top{text-align:center;border-bottom:2px solid #111;padding-bottom:18px;margin-bottom:22px}.top h1{font-size:20px;margin:0 0 5px}.top p{margin:0;color:#555}.row{display:flex;justify-content:space-between;gap:20px;padding:11px 0;border-bottom:1px solid #eee}.value{font-weight:700}.total{font-size:20px;margin-top:10px;border:0}.foot{text-align:center;margin-top:30px;color:#666;font-size:12px}@media print{body{padding:0}.box{border:0}}</style></head><body><div class="box"><div class="top"><h1>${association}</h1><p>AMVF2 — Recibo de Pagamento</p></div><div class="row"><span>Recebemos de</span><span class="value">${resident.name}</span></div><div class="row"><span>Referente a</span><span class="value">Taxa mensal — ${monthLabel(referenceMonth)}</span></div><div class="row"><span>Forma de pagamento</span><span class="value">${methods[payment.method]||payment.method||"Não informado"}</span></div><div class="row"><span>Data do pagamento</span><span class="value">${dateBR(payment.date)}</span></div><div class="row total"><span>Valor recebido</span><span class="value">${brl(payment.amount)}</span></div><div class="foot">Documento gerado pelo sistema administrativo da AMVF2.</div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);
  w.document.close();
}
function ResidentProfile({data,resident,close}){
  const fee=Number(data.settings?.taxaMensal||0);
  const pending=residentPendingMonths(resident);
  const paidMonths=(resident.paidMonths||[]).slice().sort().reverse();
  const monthlyIds=resident.monthlyPaymentIds||{};
  const monthlyIdToMonth=Object.fromEntries(Object.entries(monthlyIds).map(([month,id])=>[String(id),month]));
  const monthlyTransactions=(data.transactions||[])
    .filter(x=>Object.prototype.hasOwnProperty.call(monthlyIdToMonth,String(x.id)))
    .map(x=>({...x,statementType:"Mensalidade",referenceMonth:monthlyIdToMonth[String(x.id)],statementDescription:"Taxa Mensal"}));
  const residentPayments=(data.payments||[])
    .filter(x=>String(x.residentId||"")===String(resident.id))
    .map(p=>{
      const tx=(data.transactions||[]).find(t=>String(t.id)===String(p.transactionId));
      const booking=(data.bookings||[]).find(b=>String(b.id)===String(p.bookingId));
      return {...p,statementType:"Reserva",referenceMonth:bookingDate(booking?.date).slice(0,7),statementDescription:(tx?.description&&String(tx.description).trim())||booking?.purpose||"Pagamento de reserva",transaction:tx,booking};
    });
  const statement=[...monthlyTransactions.map(x=>({id:`m-${x.id}`,date:x.date,type:"income",category:"Taxa Mensal",description:x.statementDescription,method:x.method,amount:Number(x.amount||0),referenceMonth:x.referenceMonth,sortKey:String(x.date||"")})),...residentPayments.map(x=>({id:`r-${x.id}`,date:x.date,type:"income",category:"Reserva",description:x.statementDescription,method:x.method,amount:Number(x.amount||0),referenceMonth:x.referenceMonth,sortKey:String(x.date||"")}))]
    .sort((a,b)=>String(b.sortKey).localeCompare(String(a.sortKey)));
  const monthlyPaidTotal=monthlyTransactions.reduce((a,x)=>a+Number(x.amount||0),0);
  const reservationReceived=residentPayments.reduce((a,x)=>a+Number(x.amount||0),0);
  const totalReceived=monthlyPaidTotal+reservationReceived;
  const reservations=(data.bookings||[]).filter(x=>String(x.residentId)===String(resident.id)).sort((a,b)=>bookingDate(b.date).localeCompare(bookingDate(a.date)));
  const reservationPending=reservations.reduce((sum,b)=>{
    const total=Number(b.totalAmount||0);
    const received=(data.payments||[]).filter(p=>String(p.bookingId)===String(b.id)).reduce((a,p)=>a+Number(p.amount||0),0);
    return sum+Math.max(0,total-received);
  },0);
  const openValue=pending.length*fee+reservationPending;
  const startMonth=residentStartMonth(resident);
  const printStatement=()=>printResidentStatement({data,resident,statement,totalReceived,openValue,monthlyPaidTotal,reservationReceived});

  return <Modal title="Ficha financeira do morador" close={close}>
    <div className="profile-head"><div className="avatar"><UserRound/></div><div><h2>{resident.name}</h2><span>{resident.house?`Endereço ${resident.house}`:"Endereço não informado"}</span></div></div>
    <div className="profile-grid"><Stat t="Total recebido" v={brl(totalReceived)}/><Stat t="Mensalidades pagas" v={paidMonths.length}/><Stat t="Meses pendentes" v={pending.length}/><Stat t="Total em aberto" v={brl(openValue)}/></div>
    <div className="profile-actions no-print"><button className="btn btn-primary" onClick={printStatement}><Printer size={15}/> Imprimir / PDF do extrato</button></div>
    <div className="profile-section"><h3>Cadastro</h3><div className="profile-details"><span><b>Endereço</b>{resident.house||"Não informado"}</span><span><b>Telefone</b>{resident.phone||"Não informado"}</span><span><b>E-mail</b>{resident.email||"Não informado"}</span><span><b>Início da cobrança</b>{startMonth?monthLabel(startMonth):"Não informado"}</span><span><b>Observações</b>{resident.notes||"—"}</span></div></div>
    <div className="profile-section"><div className="profile-section-head"><h3>Extrato financeiro</h3><small>{statement.length} movimentações</small></div>
      {statement.length?<div className="resident-statement">{statement.map(x=><div className="profile-row statement-row" key={x.id}><div><span>{dateBR(x.date)} · {x.category}</span><small>{x.description}{x.referenceMonth?` · ${monthLabel(x.referenceMonth)}`:""}{x.method?` · ${x.method}`:""}</small></div><b className="positive">+ {brl(x.amount)}</b></div>)}</div>:<div className="empty-state">Nenhuma movimentação financeira vinculada a este morador.</div>}
    </div>
    <div className="profile-section"><h3>Meses pendentes</h3>{pending.length?<div className="month-chips">{pending.map(m=><span key={m}>{monthLabel(m).split(" de ")[0]}</span>)}</div>:<div className="empty-state">Nenhuma pendência.</div>}</div>
    <div className="profile-section"><div className="profile-section-head"><h3>Reservas</h3><small>Recebido: {brl(reservationReceived)}</small></div>{reservations.length?reservations.slice(0,8).map(x=>{const total=Number(x.totalAmount||0),received=(data.payments||[]).filter(p=>String(p.bookingId)===String(x.id)).reduce((a,p)=>a+Number(p.amount||0),0);return <div className="profile-row" key={x.id}><div><span>{dateBR(bookingDate(x.date))} · {x.purpose||"Reserva da sala"}</span><small>Recebido {brl(received)} · A receber {brl(Math.max(0,total-received))}</small></div><b>{brl(total)}</b></div>}):<div className="empty-state">Nenhuma reserva vinculada.</div>}</div>
  </Modal>
}
function printResidentStatement({data,resident,statement,totalReceived,openValue,monthlyPaidTotal,reservationReceived}){
  const association=data.settings?.associacao||"Associação de Moradores do Vila Floresta 2";
  const methods={pix:"Pix",cash:"Dinheiro",credit:"Cartão de crédito",debit:"Cartão de débito",transfer:"Transferência",other:"Outro"};
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
  const w=window.open("","_blank","width=800,height=900");
  if(!w){alert("O navegador bloqueou a janela do extrato. Permita pop-ups para imprimir o extrato.");return}
  const rows=statement.map(x=>`<tr><td>${esc(dateBR(x.date))}</td><td>${esc(x.category)}</td><td>${esc(x.description)}${x.referenceMonth?` — ${esc(monthLabel(x.referenceMonth))}`:""}</td><td>${esc(methods[x.method]||x.method||"—")}</td><td class="money">+ ${esc(brl(x.amount))}</td></tr>`).join("");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Extrato — ${esc(resident.name)}</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#111;max-width:900px;margin:auto}.top{text-align:center;border-bottom:2px solid #111;padding-bottom:14px;margin-bottom:18px}.top h1{margin:0;font-size:20px}.top p{margin:4px 0;color:#555}.person{padding:12px 0}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0 20px}.summary div{border:1px solid #ddd;border-radius:8px;padding:10px}.summary small{display:block;color:#666}.summary b{display:block;margin-top:4px}.section{margin-top:20px}.section h2{font-size:15px;margin:0 0 8px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;border-bottom:1px solid #ddd;padding:8px 5px;vertical-align:top}.money{text-align:right;font-weight:700}.foot{margin-top:24px;color:#666;font-size:11px;text-align:center}@media print{body{padding:0}.summary{grid-template-columns:repeat(4,1fr)}}@media(max-width:600px){.summary{grid-template-columns:repeat(2,1fr)}} </style></head><body><div class="top"><h1>${esc(association)}</h1><p>AMVF2 — Extrato financeiro do morador</p></div><div class="person"><b>${esc(resident.name)}</b><br>Endereço: ${esc(resident.house||"Não informado")}</div><div class="summary"><div><small>Total recebido</small><b>${esc(brl(totalReceived))}</b></div><div><small>Mensalidades</small><b>${esc(brl(monthlyPaidTotal))}</b></div><div><small>Reservas recebidas</small><b>${esc(brl(reservationReceived))}</b></div><div><small>Total em aberto</small><b>${esc(brl(openValue))}</b></div></div><div class="section"><h2>Movimentações financeiras</h2>${statement.length?`<table><thead><tr><th>Data</th><th>Categoria</th><th>Descrição</th><th>Forma</th><th>Valor</th></tr></thead><tbody>${rows}</tbody></table>`:`<p>Nenhuma movimentação financeira vinculada a este morador.</p>`}</div><div class="foot">Documento gerado pelo sistema administrativo da AMVF2.</div><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);
  w.document.close();
}
function MonthlyPayment({resident,month,close,save}){let[f,setF]=useState({amount:resident._monthlyFee??0,method:"pix",date:todayISO()});return <Modal title="Registrar mensalidade" close={close}><div style={{marginBottom:16,color:"#475569"}}>Morador: <b>{resident.name}</b><br/>Referência: <b>{monthLabel(month)}</b></div><F l="Valor da mensalidade"><input className="input" inputMode="decimal" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></F><F l="Forma de pagamento"><select className="input" value={f.method} onChange={e=>setF({...f,method:e.target.value})}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit">Cartão de crédito</option><option value="debit">Cartão de débito</option><option value="transfer">Transferência</option><option value="other">Outro</option></select></F><F l="Data do pagamento"><input className="input" type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></F><button className="btn btn-primary" onClick={()=>save(f)}>Registrar pagamento</button></Modal>}
function Resident({initial,close,save}){let[f,setF]=useState(initial);return <Modal title={initial.id?"Editar morador":"Novo morador"} close={close}><F l="Nome *"><input className="input" autoFocus value={f.name||""} onChange={e=>setF({...f,name:e.target.value})}/></F><F l="Endereço"><input className="input" value={f.house||""} onChange={e=>setF({...f,house:e.target.value})}/></F><F l="Telefone"><input className="input" value={f.phone||""} onChange={e=>setF({...f,phone:e.target.value})}/></F><F l="E-mail"><input className="input" type="email" value={f.email||""} onChange={e=>setF({...f,email:e.target.value})}/></F><F l="Observações"><textarea className="input" rows="3" value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/></F><label style={{display:"flex",gap:8,alignItems:"center",marginBottom:15,fontWeight:700}}><input type="checkbox" checked={!!f.exempt} onChange={e=>setF({...f,exempt:e.target.checked})}/> Isento da mensalidade</label><button className="btn btn-primary" onClick={()=>save(f)}>Salvar morador</button></Modal>}
function Config({data,refresh,setData}){let[f,setF]=useState(data.settings||{}),[busy,setBusy]=useState(false);useEffect(()=>setF(data.settings||{}),[data.settings]);let save=async()=>{setBusy(true);let x=await safe(()=>saveSettings({...f,taxaMensal:parseMoney(f.taxaMensal)}));setBusy(false);if(x){const n={...data,settings:x};saveCache(n);setData(n);await refresh();alert("Configurações salvas.")}};let imp=async e=>{const input=e.target;const file=input.files?.[0];if(!file)return;try{const x=await importBackup(file);if(!window.confirm("Restaurar este backup substituirá os dados atuais da planilha pelos dados do arquivo. Continuar?"))return;setBusy(true);const restored=await safe(()=>restoreBackup(x));if(restored){saveCache(restored);setData(restored);setF(restored.settings||{});alert("Backup restaurado na planilha com sucesso. Os dados da tela e da API estão sincronizados.")}}catch(err){alert(err.message||String(err))}finally{setBusy(false);input.value=""}};return <><Head t="Configurações" s="Dados da associação"/><div className="card" style={{padding:22,maxWidth:650}}><F l="Nome"><input className="input" value={f.associacao||""} onChange={e=>setF({...f,associacao:e.target.value})}/></F><F l="Taxa mensal"><input className="input" value={f.taxaMensal??""} onChange={e=>setF({...f,taxaMensal:e.target.value})}/></F><F l="Responsável pelos registros"><input className="input" value={f.responsavel||""} onChange={e=>setF({...f,responsavel:e.target.value})}/></F><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?"Salvando...":"Salvar configurações"}</button><div style={{marginTop:20,display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn btn-gray" disabled={busy} onClick={()=>backupData(data)}><Download/> Backup</button><label className={`btn btn-gray ${busy?"disabled":""}`} style={{cursor:busy?"wait":"pointer"}}><Upload/> {busy?"Restaurando...":"Restaurar backup"}<input hidden type="file" accept="application/json" disabled={busy} onChange={imp}/></label></div></div></>}
export default function App(){let[data,setData]=useState(loadCache());let refresh=async()=>{let x=await safe(getAll);if(x){setData(x);saveCache(x);return x}return null};useEffect(()=>{refresh()},[]);return <Layout data={data} refresh={refresh} setData={setData}/>}
